// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateApiKeyData2, CreateApiKeyErrors, CreateApiKeyResponses, CreateAssetData, CreateAssetErrors, CreateAssetResponses, CreateCheckinData, CreateCheckinErrors, CreateCheckinResponses, CreateLocationData, CreateLocationErrors, CreateLocationResponses, DeleteApiKeyData, DeleteApiKeyErrors, DeleteApiKeyResponses, DeleteAssetData, DeleteAssetErrors, DeleteAssetResponses, DeleteLocationData, DeleteLocationErrors, DeleteLocationResponses, GetApiKeyData, GetApiKeyErrors, GetApiKeyResponses, GetAssetContentData, GetAssetContentErrors, GetAssetContentResponses, GetAssetData, GetAssetErrors, GetAssetResponses, GetCheckinData, GetCheckinErrors, GetCheckinResponses, GetGroupData, GetGroupErrors, GetGroupMembershipData, GetGroupMembershipErrors, GetGroupMembershipResponses, GetGroupResponses, GetLocationData, GetLocationErrors, GetLocationResponses, GetUserData, GetUserErrors, GetUserResponses, ListApiKeysData, ListApiKeysErrors, ListApiKeysResponses, ListAssetsData, ListAssetsErrors, ListAssetsResponses, ListCheckinDepartmentsData, ListCheckinDepartmentsErrors, ListCheckinDepartmentsResponses, ListCheckinsData, ListCheckinsErrors, ListCheckinsResponses, ListGroupMembershipsData, ListGroupMembershipsErrors, ListGroupMembershipsResponses, ListGroupsData, ListGroupsErrors, ListGroupsResponses, ListLocationsData, ListLocationsErrors, ListLocationsResponses, ListUsersData, ListUsersErrors, ListUsersResponses, PatchApiKeyData, PatchApiKeyErrors, PatchApiKeyResponses, PatchAssetData, PatchAssetErrors, PatchAssetResponses, PatchLocationData, PatchLocationErrors, PatchLocationResponses, PatchUserData, PatchUserErrors, PatchUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const listApiKeys = <ThrowOnError extends boolean = false>(options?: Options<ListApiKeysData, ThrowOnError>): RequestResult<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError> => (options?.client ?? client).get<ListApiKeysResponses, ListApiKeysErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/api-keys',
    ...options
});

export const createApiKey = <ThrowOnError extends boolean = false>(options: Options<CreateApiKeyData2, ThrowOnError>): RequestResult<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError> => (options.client ?? client).post<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/api-keys',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteApiKey = <ThrowOnError extends boolean = false>(options: Options<DeleteApiKeyData, ThrowOnError>): RequestResult<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError> => (options.client ?? client).delete<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/api-keys/{id}',
    ...options
});

export const getApiKey = <ThrowOnError extends boolean = false>(options: Options<GetApiKeyData, ThrowOnError>): RequestResult<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError> => (options.client ?? client).get<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/api-keys/{id}',
    ...options
});

export const patchApiKey = <ThrowOnError extends boolean = false>(options: Options<PatchApiKeyData, ThrowOnError>): RequestResult<PatchApiKeyResponses, PatchApiKeyErrors, ThrowOnError> => (options.client ?? client).patch<PatchApiKeyResponses, PatchApiKeyErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/api-keys/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listAssets = <ThrowOnError extends boolean = false>(options?: Options<ListAssetsData, ThrowOnError>): RequestResult<ListAssetsResponses, ListAssetsErrors, ThrowOnError> => (options?.client ?? client).get<ListAssetsResponses, ListAssetsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/assets',
    ...options
});

export const createAsset = <ThrowOnError extends boolean = false>(options: Options<CreateAssetData, ThrowOnError>): RequestResult<CreateAssetResponses, CreateAssetErrors, ThrowOnError> => (options.client ?? client).post<CreateAssetResponses, CreateAssetErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/assets',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const deleteAsset = <ThrowOnError extends boolean = false>(options: Options<DeleteAssetData, ThrowOnError>): RequestResult<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError> => (options.client ?? client).delete<DeleteAssetResponses, DeleteAssetErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/assets/{id}',
    ...options
});

export const getAsset = <ThrowOnError extends boolean = false>(options: Options<GetAssetData, ThrowOnError>): RequestResult<GetAssetResponses, GetAssetErrors, ThrowOnError> => (options.client ?? client).get<GetAssetResponses, GetAssetErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/assets/{id}',
    ...options
});

export const patchAsset = <ThrowOnError extends boolean = false>(options: Options<PatchAssetData, ThrowOnError>): RequestResult<PatchAssetResponses, PatchAssetErrors, ThrowOnError> => (options.client ?? client).patch<PatchAssetResponses, PatchAssetErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/assets/{id}',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const getAssetContent = <ThrowOnError extends boolean = false>(options: Options<GetAssetContentData, ThrowOnError>): RequestResult<GetAssetContentResponses, GetAssetContentErrors, ThrowOnError> => (options.client ?? client).get<GetAssetContentResponses, GetAssetContentErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/assets/{id}/content',
    ...options
});

export const listCheckins = <ThrowOnError extends boolean = false>(options?: Options<ListCheckinsData, ThrowOnError>): RequestResult<ListCheckinsResponses, ListCheckinsErrors, ThrowOnError> => (options?.client ?? client).get<ListCheckinsResponses, ListCheckinsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/checkins',
    ...options
});

export const createCheckin = <ThrowOnError extends boolean = false>(options: Options<CreateCheckinData, ThrowOnError>): RequestResult<CreateCheckinResponses, CreateCheckinErrors, ThrowOnError> => (options.client ?? client).post<CreateCheckinResponses, CreateCheckinErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/checkins',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

export const listCheckinDepartments = <ThrowOnError extends boolean = false>(options?: Options<ListCheckinDepartmentsData, ThrowOnError>): RequestResult<ListCheckinDepartmentsResponses, ListCheckinDepartmentsErrors, ThrowOnError> => (options?.client ?? client).get<ListCheckinDepartmentsResponses, ListCheckinDepartmentsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/checkins/departments',
    ...options
});

export const getCheckin = <ThrowOnError extends boolean = false>(options: Options<GetCheckinData, ThrowOnError>): RequestResult<GetCheckinResponses, GetCheckinErrors, ThrowOnError> => (options.client ?? client).get<GetCheckinResponses, GetCheckinErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/checkins/{id}',
    ...options
});

export const listGroupMemberships = <ThrowOnError extends boolean = false>(options?: Options<ListGroupMembershipsData, ThrowOnError>): RequestResult<ListGroupMembershipsResponses, ListGroupMembershipsErrors, ThrowOnError> => (options?.client ?? client).get<ListGroupMembershipsResponses, ListGroupMembershipsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/group-memberships',
    ...options
});

export const getGroupMembership = <ThrowOnError extends boolean = false>(options: Options<GetGroupMembershipData, ThrowOnError>): RequestResult<GetGroupMembershipResponses, GetGroupMembershipErrors, ThrowOnError> => (options.client ?? client).get<GetGroupMembershipResponses, GetGroupMembershipErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/group-memberships/{id}',
    ...options
});

export const listGroups = <ThrowOnError extends boolean = false>(options?: Options<ListGroupsData, ThrowOnError>): RequestResult<ListGroupsResponses, ListGroupsErrors, ThrowOnError> => (options?.client ?? client).get<ListGroupsResponses, ListGroupsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/groups',
    ...options
});

export const getGroup = <ThrowOnError extends boolean = false>(options: Options<GetGroupData, ThrowOnError>): RequestResult<GetGroupResponses, GetGroupErrors, ThrowOnError> => (options.client ?? client).get<GetGroupResponses, GetGroupErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/groups/{id}',
    ...options
});

export const listLocations = <ThrowOnError extends boolean = false>(options?: Options<ListLocationsData, ThrowOnError>): RequestResult<ListLocationsResponses, ListLocationsErrors, ThrowOnError> => (options?.client ?? client).get<ListLocationsResponses, ListLocationsErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/locations',
    ...options
});

export const createLocation = <ThrowOnError extends boolean = false>(options: Options<CreateLocationData, ThrowOnError>): RequestResult<CreateLocationResponses, CreateLocationErrors, ThrowOnError> => (options.client ?? client).post<CreateLocationResponses, CreateLocationErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/locations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteLocation = <ThrowOnError extends boolean = false>(options: Options<DeleteLocationData, ThrowOnError>): RequestResult<DeleteLocationResponses, DeleteLocationErrors, ThrowOnError> => (options.client ?? client).delete<DeleteLocationResponses, DeleteLocationErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/locations/{id}',
    ...options
});

export const getLocation = <ThrowOnError extends boolean = false>(options: Options<GetLocationData, ThrowOnError>): RequestResult<GetLocationResponses, GetLocationErrors, ThrowOnError> => (options.client ?? client).get<GetLocationResponses, GetLocationErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/locations/{id}',
    ...options
});

export const patchLocation = <ThrowOnError extends boolean = false>(options: Options<PatchLocationData, ThrowOnError>): RequestResult<PatchLocationResponses, PatchLocationErrors, ThrowOnError> => (options.client ?? client).patch<PatchLocationResponses, PatchLocationErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/locations/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>): RequestResult<ListUsersResponses, ListUsersErrors, ThrowOnError> => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/users',
    ...options
});

export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/users/{id}',
    ...options
});

export const patchUser = <ThrowOnError extends boolean = false>(options: Options<PatchUserData, ThrowOnError>): RequestResult<PatchUserResponses, PatchUserErrors, ThrowOnError> => (options.client ?? client).patch<PatchUserResponses, PatchUserErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }, {
            in: 'cookie',
            name: 'woodgate_session',
            type: 'apiKey'
        }],
    url: '/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
