// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AccountBody = {
    effective_permissions: {
        [key: string]: string;
    };
    user: User;
};

export type AccountMutation = {
    name: string;
    password?: string;
};

export type AssignmentsOutputBody = {
    items: Array<AuthorizationAssignment>;
};

export type AttachmentUploadInputBody = {
    filename: string;
};

export type AuthorizationAssignment = {
    role_id: number;
    subject_id: number;
    subject_kind: string;
};

export type AuthorizationAssignmentMutation = {
    role_ids: Array<number>;
    subject_id: number;
    subject_kind: string;
};

export type AuthorizationDefinition = {
    display_name: string;
    resource: string;
};

export type AuthorizationRole = {
    builtin: boolean;
    created_at: string;
    description: string;
    id: number;
    key: string;
    name: string;
    permissions: {
        [key: string]: string;
    };
    updated_at: string;
};

export type AuthorizationRoleMutation = {
    description: string;
    key?: string;
    name: string;
    permissions: {
        [key: string]: string;
    };
};

export type Checkin = {
    created_at: string;
    created_by_user_id?: number;
    department: string;
    direction: string;
    id: number;
    location_id: number;
    location_name: string;
    notes: string;
    photo_file?: CheckinAttachmentFile;
    photo_object_id?: number;
    photo_url?: string;
    station_id?: number;
    user_id: number;
    user_name: string;
};

export type CheckinAttachmentFile = {
    content_type: string;
    filename: string;
    sha256: string;
    size_bytes: number;
};

export type CheckinAttachmentMutation = {
    object_id: number;
};

export type CheckinAttachmentObjectView = {
    content_type: string;
    content_url: string;
    filename: string;
    id: number;
    sha256?: string;
    size_bytes?: number;
};

export type CheckinCreate = {
    direction: 'check_in' | 'check_out';
    location_id: number;
    notes: string;
    user_id: number;
};

export type CheckinDirectUploadAction = {
    headers?: {
        [key: string]: string;
    };
    method: 'PUT';
    strategy: 'direct-put';
    url: string;
};

export type CheckinDirectUploadTarget = {
    object_id: number;
    upload: CheckinDirectUploadAction;
};

export type CheckinLocation = {
    background_file?: CheckinAttachmentFile;
    background_object_id?: number;
    background_url?: string;
    created_at: string;
    description: string;
    enabled: boolean;
    group_ids: Array<number>;
    id: number;
    logo_file?: CheckinAttachmentFile;
    logo_object_id?: number;
    logo_url?: string;
    name: string;
    notes: boolean;
    photo: boolean;
    updated_at: string;
};

export type CheckinLocationMutation = {
    background_object_id?: number;
    description: string;
    enabled: boolean;
    group_ids: Array<number>;
    logo_object_id?: number;
    name: string;
    notes: boolean;
    photo: boolean;
};

export type Department = {
    value: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail>;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type Group = {
    created_at: string;
    display_name: string;
    external_id: string;
    id: number;
    mail_nickname?: string;
    member_count: number;
    source: 'local' | 'entra';
    updated_at: string;
};

export type PageAttachmentObjectView = {
    count: number;
    items: Array<CheckinAttachmentObjectView>;
};

export type PageCheckin = {
    count: number;
    items: Array<Checkin>;
};

export type PageDepartment = {
    count: number;
    items: Array<Department>;
};

export type PageGroup = {
    count: number;
    items: Array<Group>;
};

export type PageLocation = {
    count: number;
    items: Array<CheckinLocation>;
};

export type PageStation = {
    count: number;
    items: Array<Station>;
};

export type PageUser = {
    count: number;
    items: Array<User>;
};

export type ResourcesOutputBody = {
    items: Array<AuthorizationDefinition>;
};

export type RolesOutputBody = {
    items: Array<AuthorizationRole>;
};

export type SessionBody = {
    sso_enabled: boolean;
    user?: User;
};

export type SessionCreateInputBody = {
    email: string;
    password: string;
};

export type Station = {
    app_build?: string;
    created_at: string;
    enabled: boolean;
    id: number;
    last_seen_at?: string;
    location_id: number;
    name: string;
    online: boolean;
    protocol_version?: number;
    secret_prefix: string;
    updated_at: string;
};

export type StationMutation = {
    enabled: boolean;
    location_id: number;
    name: string;
};

export type StationSecret = {
    secret: string;
    station: Station;
};

export type SyncRun = {
    duration_ms?: number;
    error?: string;
    finished_at?: string;
    groups?: number;
    id: number;
    outcome?: 'succeeded' | 'failed';
    queued_at: string;
    started_at?: string;
    trigger: 'scheduled' | 'manual';
    users?: number;
};

export type SyncStatus = {
    activity: 'idle' | 'queued' | 'running';
    current_run?: SyncRun;
    enabled: boolean;
    last_run?: SyncRun;
};

export type User = {
    access_enabled: boolean;
    created_at: string;
    deleted_at?: string;
    department?: string;
    email: string;
    external_id?: string;
    family_name?: string;
    given_name?: string;
    id: number;
    mail_nickname?: string;
    name: string;
    source: 'local' | 'entra';
    updated_at: string;
    user_principal_name?: string;
};

export type UserCreate = {
    access_enabled: boolean;
    email: string;
    name?: string;
    password: string;
};

export type UserMutation = {
    access_enabled: boolean;
    name: string;
    password?: string;
};

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type GetAccountErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * OK
     */
    200: AccountBody;
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type UpdateAccountData = {
    body: AccountMutation;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type UpdateAccountErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
    /**
     * OK
     */
    200: AccountBody;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type ListRoleAssignmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/authz/assignments';
};

export type ListRoleAssignmentsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListRoleAssignmentsError = ListRoleAssignmentsErrors[keyof ListRoleAssignmentsErrors];

export type ListRoleAssignmentsResponses = {
    /**
     * OK
     */
    200: AssignmentsOutputBody;
};

export type ListRoleAssignmentsResponse = ListRoleAssignmentsResponses[keyof ListRoleAssignmentsResponses];

export type ReplaceRoleAssignmentsData = {
    body: AuthorizationAssignmentMutation;
    path?: never;
    query?: never;
    url: '/api/authz/assignments';
};

export type ReplaceRoleAssignmentsErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type ReplaceRoleAssignmentsError = ReplaceRoleAssignmentsErrors[keyof ReplaceRoleAssignmentsErrors];

export type ReplaceRoleAssignmentsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ReplaceRoleAssignmentsResponse = ReplaceRoleAssignmentsResponses[keyof ReplaceRoleAssignmentsResponses];

export type ListAuthorizationResourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/authz/resources';
};

export type ListAuthorizationResourcesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListAuthorizationResourcesError = ListAuthorizationResourcesErrors[keyof ListAuthorizationResourcesErrors];

export type ListAuthorizationResourcesResponses = {
    /**
     * OK
     */
    200: ResourcesOutputBody;
};

export type ListAuthorizationResourcesResponse = ListAuthorizationResourcesResponses[keyof ListAuthorizationResourcesResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/authz/roles';
};

export type ListRolesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
    /**
     * OK
     */
    200: RolesOutputBody;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type CreateRoleData = {
    body: AuthorizationRoleMutation;
    path?: never;
    query?: never;
    url: '/api/authz/roles';
};

export type CreateRoleErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors];

export type CreateRoleResponses = {
    /**
     * Created
     */
    201: AuthorizationRole;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type DeleteRoleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/authz/roles/{id}';
};

export type DeleteRoleErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type GetRoleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/authz/roles/{id}';
};

export type GetRoleErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * OK
     */
    200: AuthorizationRole;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type UpdateRoleData = {
    body: AuthorizationRoleMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/authz/roles/{id}';
};

export type UpdateRoleErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * OK
     */
    200: AuthorizationRole;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type ListCheckinsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        location_id?: number;
        user_id?: number;
        direction?: 'check_in' | 'check_out';
        department?: string;
        created_from?: string;
        created_before?: string;
    };
    url: '/api/checkins';
};

export type ListCheckinsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListCheckinsError = ListCheckinsErrors[keyof ListCheckinsErrors];

export type ListCheckinsResponses = {
    /**
     * OK
     */
    200: PageCheckin;
};

export type ListCheckinsResponse = ListCheckinsResponses[keyof ListCheckinsResponses];

export type CreateCheckinData = {
    body: CheckinCreate;
    path?: never;
    query?: never;
    url: '/api/checkins';
};

export type CreateCheckinErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateCheckinError = CreateCheckinErrors[keyof CreateCheckinErrors];

export type CreateCheckinResponses = {
    /**
     * Created
     */
    201: Checkin;
};

export type CreateCheckinResponse = CreateCheckinResponses[keyof CreateCheckinResponses];

export type GetCheckinData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/checkins/{id}';
};

export type GetCheckinErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetCheckinError = GetCheckinErrors[keyof GetCheckinErrors];

export type GetCheckinResponses = {
    /**
     * OK
     */
    200: Checkin;
};

export type GetCheckinResponse = GetCheckinResponses[keyof GetCheckinResponses];

export type GetDirectorySyncData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/directory/sync';
};

export type GetDirectorySyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetDirectorySyncError = GetDirectorySyncErrors[keyof GetDirectorySyncErrors];

export type GetDirectorySyncResponses = {
    /**
     * OK
     */
    200: SyncStatus;
};

export type GetDirectorySyncResponse = GetDirectorySyncResponses[keyof GetDirectorySyncResponses];

export type TriggerDirectorySyncData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/directory/sync';
};

export type TriggerDirectorySyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type TriggerDirectorySyncError = TriggerDirectorySyncErrors[keyof TriggerDirectorySyncErrors];

export type TriggerDirectorySyncResponses = {
    /**
     * Accepted
     */
    202: SyncStatus;
};

export type TriggerDirectorySyncResponse = TriggerDirectorySyncResponses[keyof TriggerDirectorySyncResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        values?: Array<string>;
    };
    url: '/api/groups';
};

export type ListGroupsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListGroupsError = ListGroupsErrors[keyof ListGroupsErrors];

export type ListGroupsResponses = {
    /**
     * OK
     */
    200: PageGroup;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type GetGroupData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetGroupErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetGroupError = GetGroupErrors[keyof GetGroupErrors];

export type GetGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type ListLocationsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        enabled?: boolean;
    };
    url: '/api/locations';
};

export type ListLocationsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationsError = ListLocationsErrors[keyof ListLocationsErrors];

export type ListLocationsResponses = {
    /**
     * OK
     */
    200: PageLocation;
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type CreateLocationData = {
    body: CheckinLocationMutation;
    path?: never;
    query?: never;
    url: '/api/locations';
};

export type CreateLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * Created
     */
    201: CheckinLocation;
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type ListLocationBackgroundsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/locations/backgrounds';
};

export type ListLocationBackgroundsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationBackgroundsError = ListLocationBackgroundsErrors[keyof ListLocationBackgroundsErrors];

export type ListLocationBackgroundsResponses = {
    /**
     * OK
     */
    200: PageAttachmentObjectView;
};

export type ListLocationBackgroundsResponse = ListLocationBackgroundsResponses[keyof ListLocationBackgroundsResponses];

export type CreateLocationBackgroundUploadData = {
    body: AttachmentUploadInputBody;
    path?: never;
    query?: never;
    url: '/api/locations/backgrounds';
};

export type CreateLocationBackgroundUploadErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateLocationBackgroundUploadError = CreateLocationBackgroundUploadErrors[keyof CreateLocationBackgroundUploadErrors];

export type CreateLocationBackgroundUploadResponses = {
    /**
     * Created
     */
    201: CheckinDirectUploadTarget;
};

export type CreateLocationBackgroundUploadResponse = CreateLocationBackgroundUploadResponses[keyof CreateLocationBackgroundUploadResponses];

export type ListLocationLogosData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/locations/logos';
};

export type ListLocationLogosErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationLogosError = ListLocationLogosErrors[keyof ListLocationLogosErrors];

export type ListLocationLogosResponses = {
    /**
     * OK
     */
    200: PageAttachmentObjectView;
};

export type ListLocationLogosResponse = ListLocationLogosResponses[keyof ListLocationLogosResponses];

export type CreateLocationLogoUploadData = {
    body: AttachmentUploadInputBody;
    path?: never;
    query?: never;
    url: '/api/locations/logos';
};

export type CreateLocationLogoUploadErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateLocationLogoUploadError = CreateLocationLogoUploadErrors[keyof CreateLocationLogoUploadErrors];

export type CreateLocationLogoUploadResponses = {
    /**
     * Created
     */
    201: CheckinDirectUploadTarget;
};

export type CreateLocationLogoUploadResponse = CreateLocationLogoUploadResponses[keyof CreateLocationLogoUploadResponses];

export type DeleteLocationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}';
};

export type DeleteLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type DeleteLocationError = DeleteLocationErrors[keyof DeleteLocationErrors];

export type DeleteLocationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteLocationResponse = DeleteLocationResponses[keyof DeleteLocationResponses];

export type GetLocationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}';
};

export type GetLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetLocationError = GetLocationErrors[keyof GetLocationErrors];

export type GetLocationResponses = {
    /**
     * OK
     */
    200: CheckinLocation;
};

export type GetLocationResponse = GetLocationResponses[keyof GetLocationResponses];

export type UpdateLocationData = {
    body: CheckinLocationMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}';
};

export type UpdateLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type UpdateLocationError = UpdateLocationErrors[keyof UpdateLocationErrors];

export type UpdateLocationResponses = {
    /**
     * OK
     */
    200: CheckinLocation;
};

export type UpdateLocationResponse = UpdateLocationResponses[keyof UpdateLocationResponses];

export type SetLocationBackgroundData = {
    body: CheckinAttachmentMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}/background';
};

export type SetLocationBackgroundErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type SetLocationBackgroundError = SetLocationBackgroundErrors[keyof SetLocationBackgroundErrors];

export type SetLocationBackgroundResponses = {
    /**
     * OK
     */
    200: CheckinAttachmentObjectView;
};

export type SetLocationBackgroundResponse = SetLocationBackgroundResponses[keyof SetLocationBackgroundResponses];

export type SetLocationLogoData = {
    body: CheckinAttachmentMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}/logo';
};

export type SetLocationLogoErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type SetLocationLogoError = SetLocationLogoErrors[keyof SetLocationLogoErrors];

export type SetLocationLogoResponses = {
    /**
     * OK
     */
    200: CheckinAttachmentObjectView;
};

export type SetLocationLogoResponse = SetLocationLogoResponses[keyof SetLocationLogoResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type DeleteSessionErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type GetSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * OK
     */
    200: SessionBody;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type CreateSessionData = {
    body: SessionCreateInputBody;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type CreateSessionErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Too Many Requests
     */
    429: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
    /**
     * OK
     */
    200: User;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type ListStationsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        location_id?: number;
        enabled?: boolean;
    };
    url: '/api/stations';
};

export type ListStationsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListStationsError = ListStationsErrors[keyof ListStationsErrors];

export type ListStationsResponses = {
    /**
     * OK
     */
    200: PageStation;
};

export type ListStationsResponse = ListStationsResponses[keyof ListStationsResponses];

export type CreateStationData = {
    body: StationMutation;
    path?: never;
    query?: never;
    url: '/api/stations';
};

export type CreateStationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateStationError = CreateStationErrors[keyof CreateStationErrors];

export type CreateStationResponses = {
    /**
     * Created
     */
    201: StationSecret;
};

export type CreateStationResponse = CreateStationResponses[keyof CreateStationResponses];

export type DeleteStationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stations/{id}';
};

export type DeleteStationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type DeleteStationError = DeleteStationErrors[keyof DeleteStationErrors];

export type DeleteStationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteStationResponse = DeleteStationResponses[keyof DeleteStationResponses];

export type GetStationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stations/{id}';
};

export type GetStationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetStationError = GetStationErrors[keyof GetStationErrors];

export type GetStationResponses = {
    /**
     * OK
     */
    200: Station;
};

export type GetStationResponse = GetStationResponses[keyof GetStationResponses];

export type UpdateStationData = {
    body: StationMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stations/{id}';
};

export type UpdateStationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type UpdateStationError = UpdateStationErrors[keyof UpdateStationErrors];

export type UpdateStationResponses = {
    /**
     * OK
     */
    200: Station;
};

export type UpdateStationResponse = UpdateStationResponses[keyof UpdateStationResponses];

export type RotateStationSecretData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stations/{id}/key';
};

export type RotateStationSecretErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type RotateStationSecretError = RotateStationSecretErrors[keyof RotateStationSecretErrors];

export type RotateStationSecretResponses = {
    /**
     * OK
     */
    200: StationSecret;
};

export type RotateStationSecretResponse = RotateStationSecretResponses[keyof RotateStationSecretResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        values?: Array<string>;
        access_enabled?: boolean;
        source?: 'local' | 'entra';
        group_id?: number;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * OK
     */
    200: PageUser;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Created
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ListUserDepartmentsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        values?: Array<string>;
    };
    url: '/api/users/departments';
};

export type ListUserDepartmentsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListUserDepartmentsError = ListUserDepartmentsErrors[keyof ListUserDepartmentsErrors];

export type ListUserDepartmentsResponses = {
    /**
     * OK
     */
    200: PageDepartment;
};

export type ListUserDepartmentsResponse = ListUserDepartmentsResponses[keyof ListUserDepartmentsResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];
