// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type ApiKey = {
    access: Array<PermissionGrant>;
    admin: boolean;
    created_at: string;
    expires_at?: string | null;
    id: string;
    key_prefix: string;
    last_used_at?: string | null;
    name: string;
};

export type ApiKeyAccessWriteRequest = {
    access: Array<PermissionGrant>;
    admin: boolean;
};

export type ApiKeyCreateRequest = {
    expires_at?: string | null;
    name: string;
};

export type ApiKeyListResponse = {
    rows: Array<ApiKey>;
    total: number;
};

export type Asset = {
    created_at: string;
    id: string;
    name?: string | null;
    type: AssetType;
    updated_at: string;
    url: string;
};

export type AssetCreateRequest = {
    file: Blob | File;
    name?: string;
};

export type AssetListResponse = {
    rows: Array<Asset>;
    total: number;
};

export type AssetType = 'asset' | 'photo';

export type AssetUpdateRequest = {
    file?: Blob | File;
    name?: string;
};

export type Checkin = {
    asset_id?: string | null;
    created_at: string;
    created_by_id: string;
    created_by_kind: PermissionSubjectKind;
    department: string;
    direction: CheckinDirection;
    id: string;
    location_id: string;
    location_name: string;
    notes: string;
    photo_url?: string | null;
    user_display_name: string;
    user_id: string;
};

export type CheckinCreateRequest = {
    direction: CheckinDirection;
    location_id: string;
    notes?: string;
    photo?: Blob | File;
    user_id: string;
};

export type CheckinDirection = 'check_in' | 'check_out';

export type CheckinListResponse = {
    rows: Array<Checkin>;
    total: number;
};

export type CreateApiKeyData = {
    access: Array<PermissionGrant>;
    admin: boolean;
    created_at: string;
    expires_at?: string | null;
    id: string;
    key_prefix: string;
    last_used_at?: string | null;
    name: string;
    secret: string;
};

export type DepartmentOption = {
    id: string;
    name: string;
};

export type DepartmentOptionListResponse = {
    rows: Array<DepartmentOption>;
    total: number;
};

export type FieldError = {
    code?: string;
    field: string;
    message: string;
};

export type Group = {
    created_at: string;
    description: string;
    id: string;
    member_count: number;
    name: string;
    updated_at: string;
};

export type GroupListResponse = {
    rows: Array<Group>;
    total: number;
};

export type GroupMembership = {
    created_at: string;
    group_id: string;
    id: string;
    updated_at: string;
    user_id: string;
};

export type GroupMembershipListResponse = {
    rows: Array<GroupMembership>;
    total: number;
};

export type Location = {
    background_asset_id?: string | null;
    created_at: string;
    description: string;
    enabled: boolean;
    group_ids: Array<string>;
    id: string;
    logo_asset_id?: string | null;
    name: string;
    notes: boolean;
    photo: boolean;
    updated_at: string;
};

export type LocationListResponse = {
    rows: Array<Location>;
    total: number;
};

export type LocationWriteRequest = {
    background_asset_id?: string | null;
    description: string;
    enabled: boolean;
    group_ids: Array<string>;
    logo_asset_id?: string | null;
    name: string;
    notes: boolean;
    photo: boolean;
};

export type PermissionAction = 'read' | 'create' | 'write' | 'delete';

export type PermissionGrant = {
    action: PermissionAction;
    asset_type?: AssetType | null;
    location_id?: string | null;
    resource: PermissionResource;
};

export type PermissionResource = 'users' | 'groups' | 'locations' | 'checkins' | 'assets' | 'api_keys';

export type PermissionSubjectKind = 'user' | 'api_key';

export type Problem = {
    code: string;
    detail: string;
    field_errors?: Array<FieldError>;
    status: number;
    title: string;
    type: string;
};

export type Source = 'entra' | 'local';

export type User = {
    access: Array<PermissionGrant>;
    admin: boolean;
    created_at: string;
    department: string;
    display_name: string;
    id: string;
    source: Source;
    updated_at: string;
    upn: string;
};

export type UserAccessWriteRequest = {
    access: Array<PermissionGrant>;
    admin: boolean;
};

export type UserListResponse = {
    rows: Array<User>;
    total: number;
};

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
    };
    url: '/api-keys';
};

export type ListApiKeysErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * OK
     */
    200: ApiKeyListResponse;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData2 = {
    body: ApiKeyCreateRequest;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type CreateApiKeyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: CreateApiKeyData;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type DeleteApiKeyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type GetApiKeyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type GetApiKeyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetApiKeyError = GetApiKeyErrors[keyof GetApiKeyErrors];

export type GetApiKeyResponses = {
    /**
     * OK
     */
    200: ApiKey;
};

export type GetApiKeyResponse = GetApiKeyResponses[keyof GetApiKeyResponses];

export type PatchApiKeyData = {
    body: ApiKeyAccessWriteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api-keys/{id}';
};

export type PatchApiKeyErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PatchApiKeyError = PatchApiKeyErrors[keyof PatchApiKeyErrors];

export type PatchApiKeyResponses = {
    /**
     * OK
     */
    200: ApiKey;
};

export type PatchApiKeyResponse = PatchApiKeyResponses[keyof PatchApiKeyResponses];

export type ListAssetsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
        type?: AssetType;
    };
    url: '/assets';
};

export type ListAssetsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListAssetsError = ListAssetsErrors[keyof ListAssetsErrors];

export type ListAssetsResponses = {
    /**
     * OK
     */
    200: AssetListResponse;
};

export type ListAssetsResponse = ListAssetsResponses[keyof ListAssetsResponses];

export type CreateAssetData = {
    body: AssetCreateRequest;
    path?: never;
    query?: never;
    url: '/assets';
};

export type CreateAssetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type CreateAssetError = CreateAssetErrors[keyof CreateAssetErrors];

export type CreateAssetResponses = {
    /**
     * Created
     */
    201: Asset;
};

export type CreateAssetResponse = CreateAssetResponses[keyof CreateAssetResponses];

export type DeleteAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type DeleteAssetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type DeleteAssetError = DeleteAssetErrors[keyof DeleteAssetErrors];

export type DeleteAssetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAssetResponse = DeleteAssetResponses[keyof DeleteAssetResponses];

export type GetAssetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type GetAssetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetAssetError = GetAssetErrors[keyof GetAssetErrors];

export type GetAssetResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type GetAssetResponse = GetAssetResponses[keyof GetAssetResponses];

export type PatchAssetData = {
    body: AssetUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}';
};

export type PatchAssetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PatchAssetError = PatchAssetErrors[keyof PatchAssetErrors];

export type PatchAssetResponses = {
    /**
     * OK
     */
    200: Asset;
};

export type PatchAssetResponse = PatchAssetResponses[keyof PatchAssetResponses];

export type GetAssetContentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/assets/{id}/content';
};

export type GetAssetContentErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetAssetContentError = GetAssetContentErrors[keyof GetAssetContentErrors];

export type GetAssetContentResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetAssetContentResponse = GetAssetContentResponses[keyof GetAssetContentResponses];

export type ListCheckinsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
        location_id?: string;
        user_id?: string;
        direction?: CheckinDirection;
        department?: string;
        created_from?: string;
        created_to?: string;
    };
    url: '/checkins';
};

export type ListCheckinsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListCheckinsError = ListCheckinsErrors[keyof ListCheckinsErrors];

export type ListCheckinsResponses = {
    /**
     * OK
     */
    200: CheckinListResponse;
};

export type ListCheckinsResponse = ListCheckinsResponses[keyof ListCheckinsResponses];

export type CreateCheckinData = {
    body: CheckinCreateRequest;
    path?: never;
    query?: never;
    url: '/checkins';
};

export type CreateCheckinErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type CreateCheckinError = CreateCheckinErrors[keyof CreateCheckinErrors];

export type CreateCheckinResponses = {
    /**
     * Created
     */
    201: Checkin;
};

export type CreateCheckinResponse = CreateCheckinResponses[keyof CreateCheckinResponses];

export type ListCheckinDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/checkins/departments';
};

export type ListCheckinDepartmentsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListCheckinDepartmentsError = ListCheckinDepartmentsErrors[keyof ListCheckinDepartmentsErrors];

export type ListCheckinDepartmentsResponses = {
    /**
     * OK
     */
    200: DepartmentOptionListResponse;
};

export type ListCheckinDepartmentsResponse = ListCheckinDepartmentsResponses[keyof ListCheckinDepartmentsResponses];

export type GetCheckinData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/checkins/{id}';
};

export type GetCheckinErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetCheckinError = GetCheckinErrors[keyof GetCheckinErrors];

export type GetCheckinResponses = {
    /**
     * OK
     */
    200: Checkin;
};

export type GetCheckinResponse = GetCheckinResponses[keyof GetCheckinResponses];

export type ListGroupMembershipsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
        group_id?: string;
        user_id?: string;
    };
    url: '/group-memberships';
};

export type ListGroupMembershipsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListGroupMembershipsError = ListGroupMembershipsErrors[keyof ListGroupMembershipsErrors];

export type ListGroupMembershipsResponses = {
    /**
     * OK
     */
    200: GroupMembershipListResponse;
};

export type ListGroupMembershipsResponse = ListGroupMembershipsResponses[keyof ListGroupMembershipsResponses];

export type GetGroupMembershipData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/group-memberships/{id}';
};

export type GetGroupMembershipErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetGroupMembershipError = GetGroupMembershipErrors[keyof GetGroupMembershipErrors];

export type GetGroupMembershipResponses = {
    /**
     * OK
     */
    200: GroupMembership;
};

export type GetGroupMembershipResponse = GetGroupMembershipResponses[keyof GetGroupMembershipResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
    };
    url: '/groups';
};

export type ListGroupsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListGroupsError = ListGroupsErrors[keyof ListGroupsErrors];

export type ListGroupsResponses = {
    /**
     * OK
     */
    200: GroupListResponse;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type GetGroupData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/groups/{id}';
};

export type GetGroupErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetGroupError = GetGroupErrors[keyof GetGroupErrors];

export type GetGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type ListLocationsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
        enabled?: boolean;
    };
    url: '/locations';
};

export type ListLocationsErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListLocationsError = ListLocationsErrors[keyof ListLocationsErrors];

export type ListLocationsResponses = {
    /**
     * OK
     */
    200: LocationListResponse;
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type CreateLocationData = {
    body: LocationWriteRequest;
    path?: never;
    query?: never;
    url: '/locations';
};

export type CreateLocationErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * Created
     */
    201: Location;
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type DeleteLocationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type DeleteLocationErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type DeleteLocationError = DeleteLocationErrors[keyof DeleteLocationErrors];

export type DeleteLocationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteLocationResponse = DeleteLocationResponses[keyof DeleteLocationResponses];

export type GetLocationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type GetLocationErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetLocationError = GetLocationErrors[keyof GetLocationErrors];

export type GetLocationResponses = {
    /**
     * OK
     */
    200: Location;
};

export type GetLocationResponse = GetLocationResponses[keyof GetLocationResponses];

export type PatchLocationData = {
    body: LocationWriteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/locations/{id}';
};

export type PatchLocationErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PatchLocationError = PatchLocationErrors[keyof PatchLocationErrors];

export type PatchLocationResponses = {
    /**
     * OK
     */
    200: Location;
};

export type PatchLocationResponse = PatchLocationResponses[keyof PatchLocationResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        sort?: string;
        order?: 'asc' | 'desc';
        location_id?: string;
    };
    url: '/users';
};

export type ListUsersErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * OK
     */
    200: UserListResponse;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUserErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type PatchUserData = {
    body: UserAccessWriteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PatchUserErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type PatchUserError = PatchUserErrors[keyof PatchUserErrors];

export type PatchUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type PatchUserResponse = PatchUserResponses[keyof PatchUserResponses];
