// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Account = {
    api_key?: string;
    api_key_created_at?: string;
    effective_permissions: {
        [key in AuthzResource]?: 'none' | 'view' | 'edit';
    };
    user: User;
};

export type AccountMutation = {
    name: string;
    password?: string;
};

export type AppKeyCreatedKey = {
    all_locations: boolean;
    api_key: string;
    app_id: string;
    created_at: string;
    expires_at?: string;
    id: number;
    key_prefix: string;
    last_used_at?: string;
    locations: Array<AppKeyLocationSummary>;
    name: string;
    updated_at: string;
};

export type AppKeyKey = {
    all_locations: boolean;
    app_id: string;
    created_at: string;
    expires_at?: string;
    id: number;
    key_prefix: string;
    last_used_at?: string;
    locations: Array<AppKeyLocationSummary>;
    name: string;
    updated_at: string;
};

export type AppKeyLocationSummary = {
    id: number;
    name: string;
};

export type AppKeyMutation = {
    all_locations: boolean;
    expires_at?: string;
    location_ids: Array<number>;
    name: string;
};

export type AttachmentUploadInputBody = {
    filename: string;
};

export type AuthzResource = 'users' | 'groups' | 'directory' | 'locations' | 'checkins' | 'app_keys' | 'authz.roles';

export type Checkin = {
    actor_app_id: string;
    actor_kind: string;
    actor_name: string;
    created_at: string;
    created_by?: UserSummary;
    direction: string;
    id: number;
    location: CheckinLocationSummary;
    notes: string;
    person: CheckinPersonSummary;
    photo_file?: CheckinAttachmentFile;
    photo_object_id?: number;
    photo_url?: string;
};

export type CheckinAttachmentFile = {
    content_type: string;
    filename: string;
    sha256: string;
    size_bytes: number;
};

export type CheckinAttachmentMutation = {
    object_id: number;
};

export type CheckinAttachmentObjectView = {
    content_type: string;
    content_url: string;
    filename: string;
    id: number;
    sha256?: string;
    size_bytes?: number;
};

export type CheckinCreate = {
    direction: 'check_in' | 'check_out';
    location_id: number;
    notes: string;
    user_id: number;
};

export type CheckinDirectUploadTarget = {
    object_id: number;
    upload: {
        strategy: 'direct-put';
        target: UploadTarget;
    } | {
        strategy: 'multipart';
    };
};

export type CheckinLocation = {
    background_file?: CheckinAttachmentFile;
    background_object_id?: number;
    background_url?: string;
    created_at: string;
    description: string;
    enabled: boolean;
    groups: Array<GroupSummary>;
    id: number;
    logo_file?: CheckinAttachmentFile;
    logo_object_id?: number;
    logo_url?: string;
    name: string;
    notes: boolean;
    photo: boolean;
    updated_at: string;
};

export type CheckinLocationMutation = {
    background_object_id?: number;
    description: string;
    enabled: boolean;
    group_ids: Array<number>;
    logo_object_id?: number;
    name: string;
    notes: boolean;
    photo: boolean;
};

export type CheckinLocationSummary = {
    id: number;
    name: string;
};

export type CheckinPersonSummary = {
    department?: string;
    email: string;
    id: number;
    name: string;
};

export type Definition = {
    display_name: string;
    resource: AuthzResource;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail>;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type Group = {
    created_at: string;
    display_name: string;
    external_id: string;
    id: number;
    mail_nickname?: string;
    member_count: number;
    roles: Array<RoleSummary>;
    source: 'local' | 'entra';
    updated_at: string;
};

export type GroupMutation = {
    role_ids: Array<number>;
};

export type GroupSummary = {
    display_name: string;
    id: number;
    mail_nickname?: string;
    source: 'local' | 'entra';
};

export type PageAttachmentObjectView = {
    count: number;
    items: Array<CheckinAttachmentObjectView>;
};

export type PageCheckin = {
    count: number;
    items: Array<Checkin>;
};

export type PageGroup = {
    count: number;
    items: Array<Group>;
};

export type PageGroupSummary = {
    count: number;
    items: Array<GroupSummary>;
};

export type PageKey = {
    count: number;
    items: Array<AppKeyKey>;
};

export type PageLocation = {
    count: number;
    items: Array<CheckinLocation>;
};

export type PageLocationSummary = {
    count: number;
    items: Array<AppKeyLocationSummary>;
};

export type PageUser = {
    count: number;
    items: Array<User>;
};

export type Principal = {
    email: string;
    id: number;
    name: string;
};

export type ResourcesOutputBody = {
    items: Array<Definition>;
};

export type Role = {
    builtin: boolean;
    created_at: string;
    description: string;
    id: number;
    key: string;
    name: string;
    permissions: {
        [key: string]: 'none' | 'view' | 'edit';
    };
    updated_at: string;
};

export type RoleMutation = {
    description: string;
    key?: string;
    name: string;
    permissions: {
        [key: string]: 'none' | 'view' | 'edit';
    };
};

export type RoleSummary = {
    id: number;
    key: string;
    name: string;
};

export type RolesOutputBody = {
    items: Array<Role>;
};

export type SessionBody = {
    sso_enabled: boolean;
    user?: Principal;
};

export type SessionCreateInputBody = {
    email: string;
    password: string;
};

export type SyncRun = {
    duration_ms?: number;
    error?: string;
    finished_at?: string;
    groups?: number;
    id: number;
    outcome?: 'succeeded' | 'failed';
    queued_at: string;
    started_at?: string;
    trigger: 'scheduled' | 'manual';
    users?: number;
};

export type SyncStatus = {
    activity: 'idle' | 'queued' | 'running';
    current_run?: SyncRun;
    enabled: boolean;
    last_run?: SyncRun;
};

export type UploadTarget = {
    headers?: {
        [key: string]: string;
    };
    method: 'PUT';
    url: string;
};

export type User = {
    created_at: string;
    deleted_at?: string;
    department?: string;
    effective_roles: Array<RoleSummary>;
    email: string;
    external_id?: string;
    family_name?: string;
    given_name?: string;
    id: number;
    mail_nickname?: string;
    name: string;
    roles: Array<RoleSummary>;
    source: 'local' | 'entra';
    updated_at: string;
    user_principal_name?: string;
};

export type UserCreate = {
    email: string;
    name?: string;
    password: string;
    role_ids: Array<number>;
};

export type UserMutation = {
    name: string;
    password?: string;
    role_ids: Array<number>;
};

export type UserRoleListOutputBody = {
    items: Array<RoleSummary>;
};

export type UserSummary = {
    email: string;
    id: number;
    name: string;
};

export type GetAccountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type GetAccountErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetAccountError = GetAccountErrors[keyof GetAccountErrors];

export type GetAccountResponses = {
    /**
     * OK
     */
    200: Account;
};

export type GetAccountResponse = GetAccountResponses[keyof GetAccountResponses];

export type UpdateAccountData = {
    body: AccountMutation;
    path?: never;
    query?: never;
    url: '/api/account';
};

export type UpdateAccountErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateAccountError = UpdateAccountErrors[keyof UpdateAccountErrors];

export type UpdateAccountResponses = {
    /**
     * OK
     */
    200: Account;
};

export type UpdateAccountResponse = UpdateAccountResponses[keyof UpdateAccountResponses];

export type RevokeAccountApiKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account/api-key';
};

export type RevokeAccountApiKeyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type RevokeAccountApiKeyError = RevokeAccountApiKeyErrors[keyof RevokeAccountApiKeyErrors];

export type RevokeAccountApiKeyResponses = {
    /**
     * OK
     */
    200: Account;
};

export type RevokeAccountApiKeyResponse = RevokeAccountApiKeyResponses[keyof RevokeAccountApiKeyResponses];

export type RotateAccountApiKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account/api-key';
};

export type RotateAccountApiKeyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type RotateAccountApiKeyError = RotateAccountApiKeyErrors[keyof RotateAccountApiKeyErrors];

export type RotateAccountApiKeyResponses = {
    /**
     * Created
     */
    201: Account;
};

export type RotateAccountApiKeyResponse = RotateAccountApiKeyResponses[keyof RotateAccountApiKeyResponses];

export type ListAppKeysData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/app-keys';
};

export type ListAppKeysErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListAppKeysError = ListAppKeysErrors[keyof ListAppKeysErrors];

export type ListAppKeysResponses = {
    /**
     * OK
     */
    200: PageKey;
};

export type ListAppKeysResponse = ListAppKeysResponses[keyof ListAppKeysResponses];

export type CreateAppKeyData = {
    body: AppKeyMutation;
    path?: never;
    query?: never;
    url: '/api/app-keys';
};

export type CreateAppKeyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateAppKeyError = CreateAppKeyErrors[keyof CreateAppKeyErrors];

export type CreateAppKeyResponses = {
    /**
     * Created
     */
    201: AppKeyCreatedKey;
};

export type CreateAppKeyResponse = CreateAppKeyResponses[keyof CreateAppKeyResponses];

export type ListAppKeyLocationsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/app-keys/locations';
};

export type ListAppKeyLocationsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListAppKeyLocationsError = ListAppKeyLocationsErrors[keyof ListAppKeyLocationsErrors];

export type ListAppKeyLocationsResponses = {
    /**
     * OK
     */
    200: PageLocationSummary;
};

export type ListAppKeyLocationsResponse = ListAppKeyLocationsResponses[keyof ListAppKeyLocationsResponses];

export type DeleteAppKeyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/app-keys/{id}';
};

export type DeleteAppKeyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type DeleteAppKeyError = DeleteAppKeyErrors[keyof DeleteAppKeyErrors];

export type DeleteAppKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAppKeyResponse = DeleteAppKeyResponses[keyof DeleteAppKeyResponses];

export type GetAppKeyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/app-keys/{id}';
};

export type GetAppKeyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetAppKeyError = GetAppKeyErrors[keyof GetAppKeyErrors];

export type GetAppKeyResponses = {
    /**
     * OK
     */
    200: AppKeyKey;
};

export type GetAppKeyResponse = GetAppKeyResponses[keyof GetAppKeyResponses];

export type UpdateAppKeyData = {
    body: AppKeyMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/app-keys/{id}';
};

export type UpdateAppKeyErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type UpdateAppKeyError = UpdateAppKeyErrors[keyof UpdateAppKeyErrors];

export type UpdateAppKeyResponses = {
    /**
     * OK
     */
    200: AppKeyKey;
};

export type UpdateAppKeyResponse = UpdateAppKeyResponses[keyof UpdateAppKeyResponses];

export type ListAuthorizationResourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/authz/resources';
};

export type ListAuthorizationResourcesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListAuthorizationResourcesError = ListAuthorizationResourcesErrors[keyof ListAuthorizationResourcesErrors];

export type ListAuthorizationResourcesResponses = {
    /**
     * OK
     */
    200: ResourcesOutputBody;
};

export type ListAuthorizationResourcesResponse = ListAuthorizationResourcesResponses[keyof ListAuthorizationResourcesResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/authz/roles';
};

export type ListRolesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
    /**
     * OK
     */
    200: RolesOutputBody;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type CreateRoleData = {
    body: RoleMutation;
    path?: never;
    query?: never;
    url: '/api/authz/roles';
};

export type CreateRoleErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors];

export type CreateRoleResponses = {
    /**
     * Created
     */
    201: Role;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type DeleteRoleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/authz/roles/{id}';
};

export type DeleteRoleErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type GetRoleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/authz/roles/{id}';
};

export type GetRoleErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetRoleError = GetRoleErrors[keyof GetRoleErrors];

export type GetRoleResponses = {
    /**
     * OK
     */
    200: Role;
};

export type GetRoleResponse = GetRoleResponses[keyof GetRoleResponses];

export type UpdateRoleData = {
    body: RoleMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/authz/roles/{id}';
};

export type UpdateRoleErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * OK
     */
    200: Role;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];

export type ListCheckinsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        location_id?: number;
        user_id?: number;
        direction?: 'check_in' | 'check_out';
        department?: string;
        created_from?: string;
        created_before?: string;
    };
    url: '/api/checkins';
};

export type ListCheckinsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListCheckinsError = ListCheckinsErrors[keyof ListCheckinsErrors];

export type ListCheckinsResponses = {
    /**
     * OK
     */
    200: PageCheckin;
};

export type ListCheckinsResponse = ListCheckinsResponses[keyof ListCheckinsResponses];

export type CreateCheckinData = {
    body: CheckinCreate;
    path?: never;
    query?: never;
    url: '/api/checkins';
};

export type CreateCheckinErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateCheckinError = CreateCheckinErrors[keyof CreateCheckinErrors];

export type CreateCheckinResponses = {
    /**
     * Created
     */
    201: Checkin;
};

export type CreateCheckinResponse = CreateCheckinResponses[keyof CreateCheckinResponses];

export type GetCheckinData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/checkins/{id}';
};

export type GetCheckinErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetCheckinError = GetCheckinErrors[keyof GetCheckinErrors];

export type GetCheckinResponses = {
    /**
     * OK
     */
    200: Checkin;
};

export type GetCheckinResponse = GetCheckinResponses[keyof GetCheckinResponses];

export type GetDirectorySyncData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/directory/sync';
};

export type GetDirectorySyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetDirectorySyncError = GetDirectorySyncErrors[keyof GetDirectorySyncErrors];

export type GetDirectorySyncResponses = {
    /**
     * OK
     */
    200: SyncStatus;
};

export type GetDirectorySyncResponse = GetDirectorySyncResponses[keyof GetDirectorySyncResponses];

export type TriggerDirectorySyncData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/directory/sync';
};

export type TriggerDirectorySyncErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type TriggerDirectorySyncError = TriggerDirectorySyncErrors[keyof TriggerDirectorySyncErrors];

export type TriggerDirectorySyncResponses = {
    /**
     * Accepted
     */
    202: SyncStatus;
};

export type TriggerDirectorySyncResponse = TriggerDirectorySyncResponses[keyof TriggerDirectorySyncResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        values?: Array<string>;
    };
    url: '/api/groups';
};

export type ListGroupsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListGroupsError = ListGroupsErrors[keyof ListGroupsErrors];

export type ListGroupsResponses = {
    /**
     * OK
     */
    200: PageGroup;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type GetGroupData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type GetGroupErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetGroupError = GetGroupErrors[keyof GetGroupErrors];

export type GetGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type UpdateGroupData = {
    body: GroupMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/groups/{id}';
};

export type UpdateGroupErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateGroupError = UpdateGroupErrors[keyof UpdateGroupErrors];

export type UpdateGroupResponses = {
    /**
     * OK
     */
    200: Group;
};

export type UpdateGroupResponse = UpdateGroupResponses[keyof UpdateGroupResponses];

export type ListLocationsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        enabled?: boolean;
    };
    url: '/api/locations';
};

export type ListLocationsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationsError = ListLocationsErrors[keyof ListLocationsErrors];

export type ListLocationsResponses = {
    /**
     * OK
     */
    200: PageLocation;
};

export type ListLocationsResponse = ListLocationsResponses[keyof ListLocationsResponses];

export type CreateLocationData = {
    body: CheckinLocationMutation;
    path?: never;
    query?: never;
    url: '/api/locations';
};

export type CreateLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateLocationError = CreateLocationErrors[keyof CreateLocationErrors];

export type CreateLocationResponses = {
    /**
     * Created
     */
    201: CheckinLocation;
};

export type CreateLocationResponse = CreateLocationResponses[keyof CreateLocationResponses];

export type ListLocationBackgroundsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/locations/backgrounds';
};

export type ListLocationBackgroundsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationBackgroundsError = ListLocationBackgroundsErrors[keyof ListLocationBackgroundsErrors];

export type ListLocationBackgroundsResponses = {
    /**
     * OK
     */
    200: PageAttachmentObjectView;
};

export type ListLocationBackgroundsResponse = ListLocationBackgroundsResponses[keyof ListLocationBackgroundsResponses];

export type CreateLocationBackgroundUploadData = {
    body: AttachmentUploadInputBody;
    path?: never;
    query?: never;
    url: '/api/locations/backgrounds';
};

export type CreateLocationBackgroundUploadErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateLocationBackgroundUploadError = CreateLocationBackgroundUploadErrors[keyof CreateLocationBackgroundUploadErrors];

export type CreateLocationBackgroundUploadResponses = {
    /**
     * Created
     */
    201: CheckinDirectUploadTarget;
};

export type CreateLocationBackgroundUploadResponse = CreateLocationBackgroundUploadResponses[keyof CreateLocationBackgroundUploadResponses];

export type ListLocationGroupsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/locations/groups';
};

export type ListLocationGroupsErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationGroupsError = ListLocationGroupsErrors[keyof ListLocationGroupsErrors];

export type ListLocationGroupsResponses = {
    /**
     * OK
     */
    200: PageGroupSummary;
};

export type ListLocationGroupsResponse = ListLocationGroupsResponses[keyof ListLocationGroupsResponses];

export type ListLocationLogosData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
    };
    url: '/api/locations/logos';
};

export type ListLocationLogosErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListLocationLogosError = ListLocationLogosErrors[keyof ListLocationLogosErrors];

export type ListLocationLogosResponses = {
    /**
     * OK
     */
    200: PageAttachmentObjectView;
};

export type ListLocationLogosResponse = ListLocationLogosResponses[keyof ListLocationLogosResponses];

export type CreateLocationLogoUploadData = {
    body: AttachmentUploadInputBody;
    path?: never;
    query?: never;
    url: '/api/locations/logos';
};

export type CreateLocationLogoUploadErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type CreateLocationLogoUploadError = CreateLocationLogoUploadErrors[keyof CreateLocationLogoUploadErrors];

export type CreateLocationLogoUploadResponses = {
    /**
     * Created
     */
    201: CheckinDirectUploadTarget;
};

export type CreateLocationLogoUploadResponse = CreateLocationLogoUploadResponses[keyof CreateLocationLogoUploadResponses];

export type DeleteLocationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}';
};

export type DeleteLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type DeleteLocationError = DeleteLocationErrors[keyof DeleteLocationErrors];

export type DeleteLocationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteLocationResponse = DeleteLocationResponses[keyof DeleteLocationResponses];

export type GetLocationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}';
};

export type GetLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type GetLocationError = GetLocationErrors[keyof GetLocationErrors];

export type GetLocationResponses = {
    /**
     * OK
     */
    200: CheckinLocation;
};

export type GetLocationResponse = GetLocationResponses[keyof GetLocationResponses];

export type UpdateLocationData = {
    body: CheckinLocationMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}';
};

export type UpdateLocationErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type UpdateLocationError = UpdateLocationErrors[keyof UpdateLocationErrors];

export type UpdateLocationResponses = {
    /**
     * OK
     */
    200: CheckinLocation;
};

export type UpdateLocationResponse = UpdateLocationResponses[keyof UpdateLocationResponses];

export type SetLocationBackgroundData = {
    body: CheckinAttachmentMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}/background';
};

export type SetLocationBackgroundErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type SetLocationBackgroundError = SetLocationBackgroundErrors[keyof SetLocationBackgroundErrors];

export type SetLocationBackgroundResponses = {
    /**
     * OK
     */
    200: CheckinAttachmentObjectView;
};

export type SetLocationBackgroundResponse = SetLocationBackgroundResponses[keyof SetLocationBackgroundResponses];

export type SetLocationLogoData = {
    body: CheckinAttachmentMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/locations/{id}/logo';
};

export type SetLocationLogoErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type SetLocationLogoError = SetLocationLogoErrors[keyof SetLocationLogoErrors];

export type SetLocationLogoResponses = {
    /**
     * OK
     */
    200: CheckinAttachmentObjectView;
};

export type SetLocationLogoResponse = SetLocationLogoResponses[keyof SetLocationLogoResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type DeleteSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type GetSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSessionError = GetSessionErrors[keyof GetSessionErrors];

export type GetSessionResponses = {
    /**
     * OK
     */
    200: SessionBody;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type CreateSessionData = {
    body: SessionCreateInputBody;
    path?: never;
    query?: never;
    url: '/api/session';
};

export type CreateSessionErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Too Many Requests
     */
    429: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type CreateSessionError = CreateSessionErrors[keyof CreateSessionErrors];

export type CreateSessionResponses = {
    /**
     * OK
     */
    200: Principal;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        values?: Array<string>;
        role?: Array<string>;
        source?: 'local' | 'entra';
        group_id?: number;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * OK
     */
    200: PageUser;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Created
     */
    201: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type ListUserRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/roles';
};

export type ListUserRolesErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
};

export type ListUserRolesError = ListUserRolesErrors[keyof ListUserRolesErrors];

export type ListUserRolesResponses = {
    /**
     * OK
     */
    200: UserRoleListOutputBody;
};

export type ListUserRolesResponse = ListUserRolesResponses[keyof ListUserRolesResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UserMutation;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Unauthorized
     */
    401: ErrorModel;
    /**
     * Forbidden
     */
    403: ErrorModel;
    /**
     * Not Found
     */
    404: ErrorModel;
    /**
     * Conflict
     */
    409: ErrorModel;
    /**
     * Unprocessable Entity
     */
    422: ErrorModel;
    /**
     * Internal Server Error
     */
    500: ErrorModel;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];
