/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAPIKeys"];
        put?: never;
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAPIKey"];
        put?: never;
        post?: never;
        delete: operations["deleteAPIKey"];
        options?: never;
        head?: never;
        patch: operations["patchAPIKey"];
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssets"];
        put?: never;
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAsset"];
        put?: never;
        post?: never;
        delete: operations["deleteAsset"];
        options?: never;
        head?: never;
        patch: operations["patchAsset"];
        trace?: never;
    };
    "/assets/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssetContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCheckins"];
        put?: never;
        post: operations["createCheckin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCheckin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGroupMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-memberships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroupMembership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGroup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLocations"];
        put?: never;
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLocation"];
        put?: never;
        post?: never;
        delete: operations["deleteLocation"];
        options?: never;
        head?: never;
        patch: operations["patchLocation"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchUser"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIKey: {
            /** Format: uuid */
            id: string;
            name: string;
            key_prefix: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
            admin: boolean;
            access: components["schemas"]["PermissionGrant"][];
            /** Format: date-time */
            created_at: string;
        };
        APIKeyAccessWriteRequest: {
            admin: boolean;
            access: components["schemas"]["PermissionGrant"][];
        };
        APIKeyCreateRequest: {
            name: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        APIKeyListResponse: {
            rows: components["schemas"]["APIKey"][];
            /** Format: int32 */
            total: number;
        };
        Asset: {
            /** Format: uuid */
            id: string;
            name?: string | null;
            type: components["schemas"]["AssetType"];
            /** Format: uri-reference */
            url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AssetCreateRequest: {
            name?: string;
            /** Format: binary */
            file: string;
        };
        AssetListResponse: {
            rows: components["schemas"]["Asset"][];
            /** Format: int32 */
            total: number;
        };
        /** @enum {string} */
        AssetType: "asset" | "photo";
        AssetUpdateRequest: {
            name?: string;
            /** Format: binary */
            file?: string;
        };
        Checkin: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            location_id: string;
            direction: components["schemas"]["CheckinDirection"];
            notes: string;
            /** Format: uuid */
            asset_id?: string | null;
            created_by_kind: components["schemas"]["PermissionSubjectKind"];
            /** Format: uuid */
            created_by_id: string;
            /** Format: date-time */
            created_at: string;
        };
        CheckinCreateRequest: {
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            location_id: string;
            direction: components["schemas"]["CheckinDirection"];
            notes?: string;
            /** Format: binary */
            photo?: string;
        };
        /** @enum {string} */
        CheckinDirection: "check_in" | "check_out";
        CheckinListResponse: {
            rows: components["schemas"]["Checkin"][];
            /** Format: int32 */
            total: number;
        };
        CreateAPIKeyData: components["schemas"]["APIKey"] & {
            secret: string;
        };
        FieldError: {
            field: string;
            message: string;
            code?: string;
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            /** Format: int32 */
            member_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GroupListResponse: {
            rows: components["schemas"]["Group"][];
            /** Format: int32 */
            total: number;
        };
        GroupMembership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        GroupMembershipListResponse: {
            rows: components["schemas"]["GroupMembership"][];
            /** Format: int32 */
            total: number;
        };
        Location: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            enabled: boolean;
            notes: boolean;
            photo: boolean;
            /** Format: uuid */
            background_asset_id?: string | null;
            /** Format: uuid */
            logo_asset_id?: string | null;
            group_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LocationListResponse: {
            rows: components["schemas"]["Location"][];
            /** Format: int32 */
            total: number;
        };
        LocationWriteRequest: {
            name: string;
            description: string;
            enabled: boolean;
            notes: boolean;
            photo: boolean;
            /** Format: uuid */
            background_asset_id?: string | null;
            /** Format: uuid */
            logo_asset_id?: string | null;
            group_ids: string[];
        };
        /** @enum {string} */
        PermissionAction: "read" | "create" | "write" | "delete";
        PermissionGrant: {
            resource: components["schemas"]["PermissionResource"];
            action: components["schemas"]["PermissionAction"];
            /** Format: uuid */
            location_id?: string | null;
            asset_type?: components["schemas"]["AssetType"] | null;
        };
        /** @enum {string} */
        PermissionResource: "users" | "groups" | "locations" | "checkins" | "assets" | "api_keys";
        /** @enum {string} */
        PermissionSubjectKind: "user" | "api_key";
        Problem: {
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail: string;
            code: string;
            field_errors?: components["schemas"]["FieldError"][];
        };
        /** @enum {string} */
        Source: "local" | "entra";
        User: {
            /** Format: uuid */
            id: string;
            upn: string;
            display_name: string;
            department: string;
            source: components["schemas"]["Source"];
            admin: boolean;
            access: components["schemas"]["PermissionGrant"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserAccessWriteRequest: {
            admin: boolean;
            access: components["schemas"]["PermissionGrant"][];
        };
        UserListResponse: {
            rows: components["schemas"]["User"][];
            /** Format: int32 */
            total: number;
        };
    };
    responses: {
        /** @description Problem response. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        Limit: number;
        Offset: number;
        Search: string;
        Sort: string;
        Order: "asc" | "desc";
        EnabledFilter: boolean;
        GroupIdFilter: string;
        UserIdFilter: string;
        LocationIdFilter: string;
        DirectionFilter: components["schemas"]["CheckinDirection"];
        CreatedFromFilter: string;
        CreatedToFilter: string;
        AssetTypeFilter: components["schemas"]["AssetType"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAPIKeys: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyCreateRequest"];
            };
        };
        responses: {
            /** @description API key created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPIKeyData"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deleteAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    patchAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyAccessWriteRequest"];
            };
        };
        responses: {
            /** @description API key access updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listAssets: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
                type?: components["parameters"]["AssetTypeFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AssetCreateRequest"];
            };
        };
        responses: {
            /** @description Asset created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    patchAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AssetUpdateRequest"];
            };
        };
        responses: {
            /** @description Asset updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    getAssetContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset file content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listCheckins: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
                location_id?: components["parameters"]["LocationIdFilter"];
                user_id?: components["parameters"]["UserIdFilter"];
                direction?: components["parameters"]["DirectionFilter"];
                created_from?: components["parameters"]["CreatedFromFilter"];
                created_to?: components["parameters"]["CreatedToFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkin list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createCheckin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CheckinCreateRequest"];
            };
        };
        responses: {
            /** @description Checkin created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkin"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCheckin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkin detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkin"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listGroupMemberships: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
                group_id?: components["parameters"]["GroupIdFilter"];
                user_id?: components["parameters"]["UserIdFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group membership list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembershipListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getGroupMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group membership detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMembership"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listLocations: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
                enabled?: components["parameters"]["EnabledFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationWriteRequest"];
            };
        };
        responses: {
            /** @description Location created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    patchLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationWriteRequest"];
            };
        };
        responses: {
            /** @description Location updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Location"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                offset?: components["parameters"]["Offset"];
                search?: components["parameters"]["Search"];
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
                location_id?: components["parameters"]["LocationIdFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
    patchUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAccessWriteRequest"];
            };
        };
        responses: {
            /** @description User access updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
            default: components["responses"]["Problem"];
        };
    };
}
