// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
  id,
  name,
  key_prefix,
  key_hash,
  expires_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  name,
  key_prefix,
  key_hash,
  last_used_at,
  expires_at,
  created_at
`

type CreateAPIKeyParams struct {
	ID        uuid.UUID
	Name      string
	KeyPrefix string
	KeyHash   string
	ExpiresAt *time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :one
DELETE FROM api_keys
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAPIKey, id)
	err := row.Scan(&id)
	return id, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT
  id,
  name,
  key_prefix,
  key_hash,
  last_used_at,
  expires_at,
  created_at
FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
  id,
  name,
  key_prefix,
  key_hash,
  last_used_at,
  expires_at,
  created_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_keys
SET
  name = $2,
  expires_at = $3
WHERE id = $1
RETURNING
  id,
  name,
  key_prefix,
  key_hash,
  last_used_at,
  expires_at,
  created_at
`

type UpdateAPIKeyParams struct {
	ID        uuid.UUID
	Name      string
	ExpiresAt *time.Time
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKey, arg.ID, arg.Name, arg.ExpiresAt)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAPIKeyLastUsedAt = `-- name: UpdateAPIKeyLastUsedAt :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsedAt, id)
	return err
}
