// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
  id,
  name,
  type,
  content_type,
  file_extension
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  name,
  type,
  content_type,
  file_extension,
  created_at,
  updated_at
`

type CreateAssetParams struct {
	ID            uuid.UUID
	Name          pgtype.Text
	Type          string
	ContentType   string
	FileExtension string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ContentType,
		arg.FileExtension,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ContentType,
		&i.FileExtension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :one
DELETE FROM assets
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAsset, id)
	err := row.Scan(&id)
	return id, err
}

const getAsset = `-- name: GetAsset :one
SELECT
  id,
  name,
  type,
  content_type,
  file_extension,
  created_at,
  updated_at
FROM assets
WHERE id = $1
`

func (q *Queries) GetAsset(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ContentType,
		&i.FileExtension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheckinLocationIDsByAsset = `-- name: ListCheckinLocationIDsByAsset :many
SELECT location_id
FROM checkins
WHERE asset_id = $1
`

func (q *Queries) ListCheckinLocationIDsByAsset(ctx context.Context, assetID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCheckinLocationIDsByAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var location_id uuid.UUID
		if err := rows.Scan(&location_id); err != nil {
			return nil, err
		}
		items = append(items, location_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET
  name = $2,
  content_type = $3,
  file_extension = $4,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  name,
  type,
  content_type,
  file_extension,
  created_at,
  updated_at
`

type UpdateAssetParams struct {
	ID            uuid.UUID
	Name          pgtype.Text
	ContentType   string
	FileExtension string
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.ContentType,
		arg.FileExtension,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ContentType,
		&i.FileExtension,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
