// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID
	Name       string
	KeyPrefix  string
	KeyHash    string
	LastUsedAt *time.Time
	ExpiresAt  *time.Time
	CreatedAt  time.Time
}

type Asset struct {
	ID            uuid.UUID
	Name          pgtype.Text
	Type          string
	ContentType   string
	FileExtension string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Checkin struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	LocationID    uuid.UUID
	Direction     string
	Notes         string
	AssetID       *uuid.UUID
	CreatedByKind string
	CreatedByID   uuid.UUID
	CreatedAt     time.Time
}

type Group struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupMembership struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Location struct {
	ID                uuid.UUID
	Name              string
	Description       string
	Enabled           bool
	Notes             bool
	Photo             bool
	BackgroundAssetID *uuid.UUID
	LogoAssetID       *uuid.UUID
	GroupIds          []uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Permission struct {
	ID          uuid.UUID
	SubjectKind string
	SubjectID   uuid.UUID
	Resource    string
	Action      string
	LocationID  *uuid.UUID
	AssetType   pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PrincipalRole struct {
	ID            uuid.UUID
	PrincipalKind string
	PrincipalID   uuid.UUID
	Role          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID          uuid.UUID
	Upn         string
	DisplayName string
	Department  string
	Source      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
