// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions (
  id,
  subject_kind,
  subject_id,
  resource,
  action,
  location_id,
  asset_type
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreatePermissionParams struct {
	ID          uuid.UUID
	SubjectKind string
	SubjectID   uuid.UUID
	Resource    string
	Action      string
	LocationID  *uuid.UUID
	AssetType   pgtype.Text
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission,
		arg.ID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Resource,
		arg.Action,
		arg.LocationID,
		arg.AssetType,
	)
	return err
}

const deletePermissionsBySubject = `-- name: DeletePermissionsBySubject :exec
DELETE FROM permissions
WHERE subject_kind = $1
  AND subject_id = $2
`

type DeletePermissionsBySubjectParams struct {
	SubjectKind string
	SubjectID   uuid.UUID
}

func (q *Queries) DeletePermissionsBySubject(ctx context.Context, arg DeletePermissionsBySubjectParams) error {
	_, err := q.db.Exec(ctx, deletePermissionsBySubject, arg.SubjectKind, arg.SubjectID)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT
  id,
  subject_kind,
  subject_id,
  resource,
  action,
  location_id,
  asset_type,
  created_at,
  updated_at
FROM permissions
ORDER BY subject_kind, subject_id, resource, action, location_id NULLS FIRST, asset_type NULLS FIRST
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Resource,
			&i.Action,
			&i.LocationID,
			&i.AssetType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsBySubjects = `-- name: ListPermissionsBySubjects :many
SELECT
  id,
  subject_kind,
  subject_id,
  resource,
  action,
  location_id,
  asset_type,
  created_at,
  updated_at
FROM permissions
WHERE subject_kind = $1
  AND subject_id = ANY($2::UUID[])
ORDER BY subject_id, resource, location_id NULLS FIRST, asset_type NULLS FIRST
`

type ListPermissionsBySubjectsParams struct {
	SubjectKind string
	SubjectIds  []uuid.UUID
}

func (q *Queries) ListPermissionsBySubjects(ctx context.Context, arg ListPermissionsBySubjectsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsBySubjects, arg.SubjectKind, arg.SubjectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Resource,
			&i.Action,
			&i.LocationID,
			&i.AssetType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
