// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkins.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCheckin = `-- name: CreateCheckin :one
INSERT INTO checkins (
  id,
  user_id,
  location_id,
  direction,
  notes,
  asset_id,
  created_by_kind,
  created_by_id
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING
  id,
  user_id,
  location_id,
  direction,
  notes,
  asset_id,
  created_by_kind,
  created_by_id,
  created_at
`

type CreateCheckinParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	LocationID    uuid.UUID
	Direction     string
	Notes         string
	AssetID       *uuid.UUID
	CreatedByKind string
	CreatedByID   uuid.UUID
}

func (q *Queries) CreateCheckin(ctx context.Context, arg CreateCheckinParams) (Checkin, error) {
	row := q.db.QueryRow(ctx, createCheckin,
		arg.ID,
		arg.UserID,
		arg.LocationID,
		arg.Direction,
		arg.Notes,
		arg.AssetID,
		arg.CreatedByKind,
		arg.CreatedByID,
	)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.Direction,
		&i.Notes,
		&i.AssetID,
		&i.CreatedByKind,
		&i.CreatedByID,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckin = `-- name: GetCheckin :one
SELECT
  c.id,
  c.user_id,
  c.location_id,
  c.direction,
  c.notes,
  c.asset_id,
  c.created_by_kind,
  c.created_by_id,
  c.created_at
FROM checkins AS c
WHERE c.id = $1
`

func (q *Queries) GetCheckin(ctx context.Context, id uuid.UUID) (Checkin, error) {
	row := q.db.QueryRow(ctx, getCheckin, id)
	var i Checkin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocationID,
		&i.Direction,
		&i.Notes,
		&i.AssetID,
		&i.CreatedByKind,
		&i.CreatedByID,
		&i.CreatedAt,
	)
	return i, err
}
