// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entrasync.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const convertMissingEntraUsersToLocal = `-- name: ConvertMissingEntraUsersToLocal :exec
UPDATE users
SET
  source = 'local',
  updated_at = NOW()
WHERE source = 'entra'
  AND NOT (id = ANY($1::UUID[]))
`

func (q *Queries) ConvertMissingEntraUsersToLocal(ctx context.Context, userIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, convertMissingEntraUsersToLocal, userIds)
	return err
}

const deleteAllGroupMemberships = `-- name: DeleteAllGroupMemberships :exec
DELETE FROM group_memberships
`

func (q *Queries) DeleteAllGroupMemberships(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllGroupMemberships)
	return err
}

const deleteMissingGroups = `-- name: DeleteMissingGroups :exec
DELETE FROM groups
WHERE NOT (id = ANY($1::UUID[]))
`

func (q *Queries) DeleteMissingGroups(ctx context.Context, groupIds []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMissingGroups, groupIds)
	return err
}
