// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"time"

	uuid "github.com/google/uuid"
)

const getGroup = `-- name: GetGroup :one
SELECT
  g.id,
  g.name,
  g.description,
  COALESCE(member_counts.member_count, 0)::INT4 AS member_count,
  g.created_at,
  g.updated_at
FROM groups AS g
LEFT JOIN (
  SELECT group_id, COUNT(*)::INT4 AS member_count
  FROM group_memberships
  GROUP BY group_id
) AS member_counts
  ON member_counts.group_id = g.id
WHERE g.id = $1
`

type GetGroupRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	MemberCount int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGroup = `-- name: UpsertGroup :one
INSERT INTO groups (
  id,
  name,
  description
)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  updated_at = NOW()
RETURNING
  id,
  name,
  description,
  created_at,
  updated_at
`

type UpsertGroupParams struct {
	ID          uuid.UUID
	Name        string
	Description string
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, upsertGroup, arg.ID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
