// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  id,
  name,
  description,
  enabled,
  notes,
  photo,
  background_asset_id,
  logo_asset_id,
  group_ids
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id,
  name,
  description,
  enabled,
  notes,
  photo,
  background_asset_id,
  logo_asset_id,
  group_ids,
  created_at,
  updated_at
`

type CreateLocationParams struct {
	ID                uuid.UUID
	Name              string
	Description       string
	Enabled           bool
	Notes             bool
	Photo             bool
	BackgroundAssetID *uuid.UUID
	LogoAssetID       *uuid.UUID
	GroupIds          []uuid.UUID
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Notes,
		arg.Photo,
		arg.BackgroundAssetID,
		arg.LogoAssetID,
		arg.GroupIds,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Notes,
		&i.Photo,
		&i.BackgroundAssetID,
		&i.LogoAssetID,
		&i.GroupIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :one
DELETE FROM locations
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteLocation, id)
	err := row.Scan(&id)
	return id, err
}

const getLocation = `-- name: GetLocation :one
SELECT
  id,
  name,
  description,
  enabled,
  notes,
  photo,
  background_asset_id,
  logo_asset_id,
  group_ids,
  created_at,
  updated_at
FROM locations
WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Notes,
		&i.Photo,
		&i.BackgroundAssetID,
		&i.LogoAssetID,
		&i.GroupIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
  name = $2,
  description = $3,
  enabled = $4,
  notes = $5,
  photo = $6,
  background_asset_id = $7,
  logo_asset_id = $8,
  group_ids = $9,
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  name,
  description,
  enabled,
  notes,
  photo,
  background_asset_id,
  logo_asset_id,
  group_ids,
  created_at,
  updated_at
`

type UpdateLocationParams struct {
	ID                uuid.UUID
	Name              string
	Description       string
	Enabled           bool
	Notes             bool
	Photo             bool
	BackgroundAssetID *uuid.UUID
	LogoAssetID       *uuid.UUID
	GroupIds          []uuid.UUID
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Enabled,
		arg.Notes,
		arg.Photo,
		arg.BackgroundAssetID,
		arg.LogoAssetID,
		arg.GroupIds,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
		&i.Notes,
		&i.Photo,
		&i.BackgroundAssetID,
		&i.LogoAssetID,
		&i.GroupIds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
