// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const addSyncedGroupMembership = `-- name: AddSyncedGroupMembership :exec
INSERT INTO group_memberships (
  id,
  group_id,
  user_id
)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (group_id, user_id) DO UPDATE SET
  updated_at = NOW()
`

type AddSyncedGroupMembershipParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) AddSyncedGroupMembership(ctx context.Context, arg AddSyncedGroupMembershipParams) error {
	_, err := q.db.Exec(ctx, addSyncedGroupMembership, arg.ID, arg.GroupID, arg.UserID)
	return err
}

const createGroupMembership = `-- name: CreateGroupMembership :one
INSERT INTO group_memberships (
  id,
  group_id,
  user_id
)
VALUES (
  $1,
  $2,
  $3
)
RETURNING
  id,
  group_id,
  user_id,
  created_at,
  updated_at
`

type CreateGroupMembershipParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CreateGroupMembership(ctx context.Context, arg CreateGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, createGroupMembership, arg.ID, arg.GroupID, arg.UserID)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMembership = `-- name: GetGroupMembership :one
SELECT
  gm.id,
  gm.group_id,
  gm.user_id,
  gm.created_at,
  gm.updated_at
FROM group_memberships AS gm
WHERE gm.id = $1
`

func (q *Queries) GetGroupMembership(ctx context.Context, id uuid.UUID) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, getGroupMembership, id)
	var i GroupMembership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
