// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: principal_roles.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createPrincipalRole = `-- name: CreatePrincipalRole :exec
INSERT INTO principal_roles (
  id,
  principal_kind,
  principal_id,
  role
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type CreatePrincipalRoleParams struct {
	ID            uuid.UUID
	PrincipalKind string
	PrincipalID   uuid.UUID
	Role          string
}

func (q *Queries) CreatePrincipalRole(ctx context.Context, arg CreatePrincipalRoleParams) error {
	_, err := q.db.Exec(ctx, createPrincipalRole,
		arg.ID,
		arg.PrincipalKind,
		arg.PrincipalID,
		arg.Role,
	)
	return err
}

const deletePrincipalRolesByPrincipal = `-- name: DeletePrincipalRolesByPrincipal :exec
DELETE FROM principal_roles
WHERE principal_kind = $1
  AND principal_id = $2
`

type DeletePrincipalRolesByPrincipalParams struct {
	PrincipalKind string
	PrincipalID   uuid.UUID
}

func (q *Queries) DeletePrincipalRolesByPrincipal(ctx context.Context, arg DeletePrincipalRolesByPrincipalParams) error {
	_, err := q.db.Exec(ctx, deletePrincipalRolesByPrincipal, arg.PrincipalKind, arg.PrincipalID)
	return err
}

const listPrincipalRoles = `-- name: ListPrincipalRoles :many
SELECT
  id,
  principal_kind,
  principal_id,
  role,
  created_at,
  updated_at
FROM principal_roles
ORDER BY principal_kind, principal_id, role
`

func (q *Queries) ListPrincipalRoles(ctx context.Context) ([]PrincipalRole, error) {
	rows, err := q.db.Query(ctx, listPrincipalRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrincipalRole
	for rows.Next() {
		var i PrincipalRole
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalKind,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalRolesByPrincipals = `-- name: ListPrincipalRolesByPrincipals :many
SELECT
  id,
  principal_kind,
  principal_id,
  role,
  created_at,
  updated_at
FROM principal_roles
WHERE principal_kind = $1
  AND principal_id = ANY($2::UUID[])
ORDER BY principal_id, role
`

type ListPrincipalRolesByPrincipalsParams struct {
	PrincipalKind string
	PrincipalIds  []uuid.UUID
}

func (q *Queries) ListPrincipalRolesByPrincipals(ctx context.Context, arg ListPrincipalRolesByPrincipalsParams) ([]PrincipalRole, error) {
	rows, err := q.db.Query(ctx, listPrincipalRolesByPrincipals, arg.PrincipalKind, arg.PrincipalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrincipalRole
	for rows.Next() {
		var i PrincipalRole
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalKind,
			&i.PrincipalID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
