// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT
  id,
  upn,
  display_name,
  department,
  source,
  created_at,
  updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Upn,
		&i.DisplayName,
		&i.Department,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUPN = `-- name: GetUserByUPN :one
SELECT
  id,
  upn,
  display_name,
  department,
  source,
  created_at,
  updated_at
FROM users
WHERE lower(upn) = lower($1)
`

func (q *Queries) GetUserByUPN(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUPN, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Upn,
		&i.DisplayName,
		&i.Department,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
  id,
  upn,
  display_name,
  department,
  source
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (id) DO UPDATE SET
  upn = EXCLUDED.upn,
  display_name = EXCLUDED.display_name,
  department = EXCLUDED.department,
  source = EXCLUDED.source,
  updated_at = NOW()
RETURNING
  id,
  upn,
  display_name,
  department,
  source,
  created_at,
  updated_at
`

type UpsertUserParams struct {
	ID          uuid.UUID
	Upn         string
	DisplayName string
	Department  string
	Source      string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Upn,
		arg.DisplayName,
		arg.Department,
		arg.Source,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Upn,
		&i.DisplayName,
		&i.Department,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
