// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes  = "apiKeyAuth.Scopes"
	SessionAuthScopes = "sessionAuth.Scopes"
)

// Defines values for AssetType.
const (
	AssetTypeAsset AssetType = "asset"
	AssetTypePhoto AssetType = "photo"
)

// Valid indicates whether the value is a known member of the AssetType enum.
func (e AssetType) Valid() bool {
	switch e {
	case AssetTypeAsset:
		return true
	case AssetTypePhoto:
		return true
	default:
		return false
	}
}

// Defines values for CheckinDirection.
const (
	CheckIn  CheckinDirection = "check_in"
	CheckOut CheckinDirection = "check_out"
)

// Valid indicates whether the value is a known member of the CheckinDirection enum.
func (e CheckinDirection) Valid() bool {
	switch e {
	case CheckIn:
		return true
	case CheckOut:
		return true
	default:
		return false
	}
}

// Defines values for PermissionAction.
const (
	Create PermissionAction = "create"
	Delete PermissionAction = "delete"
	Read   PermissionAction = "read"
	Write  PermissionAction = "write"
)

// Valid indicates whether the value is a known member of the PermissionAction enum.
func (e PermissionAction) Valid() bool {
	switch e {
	case Create:
		return true
	case Delete:
		return true
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// Defines values for PermissionResource.
const (
	ApiKeys   PermissionResource = "api_keys"
	Assets    PermissionResource = "assets"
	Checkins  PermissionResource = "checkins"
	Groups    PermissionResource = "groups"
	Locations PermissionResource = "locations"
	Users     PermissionResource = "users"
)

// Valid indicates whether the value is a known member of the PermissionResource enum.
func (e PermissionResource) Valid() bool {
	switch e {
	case ApiKeys:
		return true
	case Assets:
		return true
	case Checkins:
		return true
	case Groups:
		return true
	case Locations:
		return true
	case Users:
		return true
	default:
		return false
	}
}

// Defines values for PermissionSubjectKind.
const (
	PermissionSubjectKindApiKey PermissionSubjectKind = "api_key"
	PermissionSubjectKindUser   PermissionSubjectKind = "user"
)

// Valid indicates whether the value is a known member of the PermissionSubjectKind enum.
func (e PermissionSubjectKind) Valid() bool {
	switch e {
	case PermissionSubjectKindApiKey:
		return true
	case PermissionSubjectKindUser:
		return true
	default:
		return false
	}
}

// Defines values for Source.
const (
	Entra Source = "entra"
	Local Source = "local"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case Entra:
		return true
	case Local:
		return true
	default:
		return false
	}
}

// Defines values for Order.
const (
	OrderAsc  Order = "asc"
	OrderDesc Order = "desc"
)

// Valid indicates whether the value is a known member of the Order enum.
func (e Order) Valid() bool {
	switch e {
	case OrderAsc:
		return true
	case OrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListAPIKeysParamsOrder.
const (
	ListAPIKeysParamsOrderAsc  ListAPIKeysParamsOrder = "asc"
	ListAPIKeysParamsOrderDesc ListAPIKeysParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListAPIKeysParamsOrder enum.
func (e ListAPIKeysParamsOrder) Valid() bool {
	switch e {
	case ListAPIKeysParamsOrderAsc:
		return true
	case ListAPIKeysParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsOrder.
const (
	ListAssetsParamsOrderAsc  ListAssetsParamsOrder = "asc"
	ListAssetsParamsOrderDesc ListAssetsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsOrder enum.
func (e ListAssetsParamsOrder) Valid() bool {
	switch e {
	case ListAssetsParamsOrderAsc:
		return true
	case ListAssetsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListCheckinsParamsOrder.
const (
	ListCheckinsParamsOrderAsc  ListCheckinsParamsOrder = "asc"
	ListCheckinsParamsOrderDesc ListCheckinsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListCheckinsParamsOrder enum.
func (e ListCheckinsParamsOrder) Valid() bool {
	switch e {
	case ListCheckinsParamsOrderAsc:
		return true
	case ListCheckinsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListGroupMembershipsParamsOrder.
const (
	ListGroupMembershipsParamsOrderAsc  ListGroupMembershipsParamsOrder = "asc"
	ListGroupMembershipsParamsOrderDesc ListGroupMembershipsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListGroupMembershipsParamsOrder enum.
func (e ListGroupMembershipsParamsOrder) Valid() bool {
	switch e {
	case ListGroupMembershipsParamsOrderAsc:
		return true
	case ListGroupMembershipsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListGroupsParamsOrder.
const (
	ListGroupsParamsOrderAsc  ListGroupsParamsOrder = "asc"
	ListGroupsParamsOrderDesc ListGroupsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListGroupsParamsOrder enum.
func (e ListGroupsParamsOrder) Valid() bool {
	switch e {
	case ListGroupsParamsOrderAsc:
		return true
	case ListGroupsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListLocationsParamsOrder.
const (
	ListLocationsParamsOrderAsc  ListLocationsParamsOrder = "asc"
	ListLocationsParamsOrderDesc ListLocationsParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListLocationsParamsOrder enum.
func (e ListLocationsParamsOrder) Valid() bool {
	switch e {
	case ListLocationsParamsOrderAsc:
		return true
	case ListLocationsParamsOrderDesc:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsOrder.
const (
	ListUsersParamsOrderAsc  ListUsersParamsOrder = "asc"
	ListUsersParamsOrderDesc ListUsersParamsOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListUsersParamsOrder enum.
func (e ListUsersParamsOrder) Valid() bool {
	switch e {
	case ListUsersParamsOrderAsc:
		return true
	case ListUsersParamsOrderDesc:
		return true
	default:
		return false
	}
}

// APIKey defines model for APIKey.
type APIKey struct {
	Access     []PermissionGrant  `json:"access"`
	Admin      bool               `json:"admin"`
	CreatedAt  time.Time          `json:"created_at"`
	ExpiresAt  *time.Time         `json:"expires_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	KeyPrefix  string             `json:"key_prefix"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`
}

// APIKeyAccessWriteRequest defines model for APIKeyAccessWriteRequest.
type APIKeyAccessWriteRequest struct {
	Access []PermissionGrant `json:"access"`
	Admin  bool              `json:"admin"`
}

// APIKeyCreateRequest defines model for APIKeyCreateRequest.
type APIKeyCreateRequest struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Name      string     `json:"name"`
}

// APIKeyListResponse defines model for APIKeyListResponse.
type APIKeyListResponse struct {
	Rows  []APIKey `json:"rows"`
	Total int32    `json:"total"`
}

// Asset defines model for Asset.
type Asset struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      *string            `json:"name,omitempty"`
	Type      AssetType          `json:"type"`
	UpdatedAt time.Time          `json:"updated_at"`
	Url       string             `json:"url"`
}

// AssetCreateRequest defines model for AssetCreateRequest.
type AssetCreateRequest struct {
	File openapi_types.File `json:"file"`
	Name *string            `json:"name,omitempty"`
}

// AssetListResponse defines model for AssetListResponse.
type AssetListResponse struct {
	Rows  []Asset `json:"rows"`
	Total int32   `json:"total"`
}

// AssetType defines model for AssetType.
type AssetType string

// AssetUpdateRequest defines model for AssetUpdateRequest.
type AssetUpdateRequest struct {
	File *openapi_types.File `json:"file,omitempty"`
	Name *string             `json:"name,omitempty"`
}

// Checkin defines model for Checkin.
type Checkin struct {
	AssetId       *openapi_types.UUID   `json:"asset_id,omitempty"`
	CreatedAt     time.Time             `json:"created_at"`
	CreatedById   openapi_types.UUID    `json:"created_by_id"`
	CreatedByKind PermissionSubjectKind `json:"created_by_kind"`
	Direction     CheckinDirection      `json:"direction"`
	Id            openapi_types.UUID    `json:"id"`
	LocationId    openapi_types.UUID    `json:"location_id"`
	Notes         string                `json:"notes"`
	UserId        openapi_types.UUID    `json:"user_id"`
}

// CheckinCreateRequest defines model for CheckinCreateRequest.
type CheckinCreateRequest struct {
	Direction  CheckinDirection    `json:"direction"`
	LocationId openapi_types.UUID  `json:"location_id"`
	Notes      *string             `json:"notes,omitempty"`
	Photo      *openapi_types.File `json:"photo,omitempty"`
	UserId     openapi_types.UUID  `json:"user_id"`
}

// CheckinDirection defines model for CheckinDirection.
type CheckinDirection string

// CheckinListResponse defines model for CheckinListResponse.
type CheckinListResponse struct {
	Rows  []Checkin `json:"rows"`
	Total int32     `json:"total"`
}

// CreateAPIKeyData defines model for CreateAPIKeyData.
type CreateAPIKeyData struct {
	Access     []PermissionGrant  `json:"access"`
	Admin      bool               `json:"admin"`
	CreatedAt  time.Time          `json:"created_at"`
	ExpiresAt  *time.Time         `json:"expires_at,omitempty"`
	Id         openapi_types.UUID `json:"id"`
	KeyPrefix  string             `json:"key_prefix"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`
	Secret     string             `json:"secret"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Code    *string `json:"code,omitempty"`
	Field   string  `json:"field"`
	Message string  `json:"message"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   time.Time          `json:"created_at"`
	Description string             `json:"description"`
	Id          openapi_types.UUID `json:"id"`
	MemberCount int32              `json:"member_count"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Rows  []Group `json:"rows"`
	Total int32   `json:"total"`
}

// GroupMembership defines model for GroupMembership.
type GroupMembership struct {
	CreatedAt time.Time          `json:"created_at"`
	GroupId   openapi_types.UUID `json:"group_id"`
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// GroupMembershipListResponse defines model for GroupMembershipListResponse.
type GroupMembershipListResponse struct {
	Rows  []GroupMembership `json:"rows"`
	Total int32             `json:"total"`
}

// Location defines model for Location.
type Location struct {
	BackgroundAssetId *openapi_types.UUID  `json:"background_asset_id,omitempty"`
	CreatedAt         time.Time            `json:"created_at"`
	Description       string               `json:"description"`
	Enabled           bool                 `json:"enabled"`
	GroupIds          []openapi_types.UUID `json:"group_ids"`
	Id                openapi_types.UUID   `json:"id"`
	LogoAssetId       *openapi_types.UUID  `json:"logo_asset_id,omitempty"`
	Name              string               `json:"name"`
	Notes             bool                 `json:"notes"`
	Photo             bool                 `json:"photo"`
	UpdatedAt         time.Time            `json:"updated_at"`
}

// LocationListResponse defines model for LocationListResponse.
type LocationListResponse struct {
	Rows  []Location `json:"rows"`
	Total int32      `json:"total"`
}

// LocationWriteRequest defines model for LocationWriteRequest.
type LocationWriteRequest struct {
	BackgroundAssetId *openapi_types.UUID  `json:"background_asset_id,omitempty"`
	Description       string               `json:"description"`
	Enabled           bool                 `json:"enabled"`
	GroupIds          []openapi_types.UUID `json:"group_ids"`
	LogoAssetId       *openapi_types.UUID  `json:"logo_asset_id,omitempty"`
	Name              string               `json:"name"`
	Notes             bool                 `json:"notes"`
	Photo             bool                 `json:"photo"`
}

// PermissionAction defines model for PermissionAction.
type PermissionAction string

// PermissionGrant defines model for PermissionGrant.
type PermissionGrant struct {
	Action     PermissionAction    `json:"action"`
	AssetType  *AssetType          `json:"asset_type,omitempty"`
	LocationId *openapi_types.UUID `json:"location_id,omitempty"`
	Resource   PermissionResource  `json:"resource"`
}

// PermissionResource defines model for PermissionResource.
type PermissionResource string

// PermissionSubjectKind defines model for PermissionSubjectKind.
type PermissionSubjectKind string

// Problem defines model for Problem.
type Problem struct {
	Code        string        `json:"code"`
	Detail      string        `json:"detail"`
	FieldErrors *[]FieldError `json:"field_errors,omitempty"`
	Status      int32         `json:"status"`
	Title       string        `json:"title"`
	Type        string        `json:"type"`
}

// Source defines model for Source.
type Source string

// User defines model for User.
type User struct {
	Access      []PermissionGrant  `json:"access"`
	Admin       bool               `json:"admin"`
	CreatedAt   time.Time          `json:"created_at"`
	Department  string             `json:"department"`
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Source      Source             `json:"source"`
	UpdatedAt   time.Time          `json:"updated_at"`
	Upn         string             `json:"upn"`
}

// UserAccessWriteRequest defines model for UserAccessWriteRequest.
type UserAccessWriteRequest struct {
	Access []PermissionGrant `json:"access"`
	Admin  bool              `json:"admin"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Rows  []User `json:"rows"`
	Total int32  `json:"total"`
}

// AssetTypeFilter defines model for AssetTypeFilter.
type AssetTypeFilter = AssetType

// CreatedFromFilter defines model for CreatedFromFilter.
type CreatedFromFilter = time.Time

// CreatedToFilter defines model for CreatedToFilter.
type CreatedToFilter = time.Time

// DirectionFilter defines model for DirectionFilter.
type DirectionFilter = CheckinDirection

// EnabledFilter defines model for EnabledFilter.
type EnabledFilter = bool

// GroupIdFilter defines model for GroupIdFilter.
type GroupIdFilter = openapi_types.UUID

// Id defines model for Id.
type Id = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int32

// LocationIdFilter defines model for LocationIdFilter.
type LocationIdFilter = openapi_types.UUID

// Offset defines model for Offset.
type Offset = int32

// Order defines model for Order.
type Order string

// Search defines model for Search.
type Search = string

// Sort defines model for Sort.
type Sort = string

// UserIdFilter defines model for UserIdFilter.
type UserIdFilter = openapi_types.UUID

// NotFound defines model for NotFound.
type NotFound = Problem

// ListAPIKeysParams defines parameters for ListAPIKeys.
type ListAPIKeysParams struct {
	Limit  *Limit                  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset                 `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search                 `form:"search,omitempty" json:"search,omitempty"`
	Sort   *Sort                   `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *ListAPIKeysParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListAPIKeysParamsOrder defines parameters for ListAPIKeys.
type ListAPIKeysParamsOrder string

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	Limit  *Limit                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset                `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search                `form:"search,omitempty" json:"search,omitempty"`
	Sort   *Sort                  `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *ListAssetsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Type   *AssetTypeFilter       `form:"type,omitempty" json:"type,omitempty"`
}

// ListAssetsParamsOrder defines parameters for ListAssets.
type ListAssetsParamsOrder string

// ListCheckinsParams defines parameters for ListCheckins.
type ListCheckinsParams struct {
	Limit       *Limit                   `form:"limit,omitempty" json:"limit,omitempty"`
	Offset      *Offset                  `form:"offset,omitempty" json:"offset,omitempty"`
	Search      *Search                  `form:"search,omitempty" json:"search,omitempty"`
	Sort        *Sort                    `form:"sort,omitempty" json:"sort,omitempty"`
	Order       *ListCheckinsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	LocationId  *LocationIdFilter        `form:"location_id,omitempty" json:"location_id,omitempty"`
	UserId      *UserIdFilter            `form:"user_id,omitempty" json:"user_id,omitempty"`
	Direction   *DirectionFilter         `form:"direction,omitempty" json:"direction,omitempty"`
	CreatedFrom *CreatedFromFilter       `form:"created_from,omitempty" json:"created_from,omitempty"`
	CreatedTo   *CreatedToFilter         `form:"created_to,omitempty" json:"created_to,omitempty"`
}

// ListCheckinsParamsOrder defines parameters for ListCheckins.
type ListCheckinsParamsOrder string

// ListGroupMembershipsParams defines parameters for ListGroupMemberships.
type ListGroupMembershipsParams struct {
	Limit   *Limit                           `form:"limit,omitempty" json:"limit,omitempty"`
	Offset  *Offset                          `form:"offset,omitempty" json:"offset,omitempty"`
	Search  *Search                          `form:"search,omitempty" json:"search,omitempty"`
	Sort    *Sort                            `form:"sort,omitempty" json:"sort,omitempty"`
	Order   *ListGroupMembershipsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	GroupId *GroupIdFilter                   `form:"group_id,omitempty" json:"group_id,omitempty"`
	UserId  *UserIdFilter                    `form:"user_id,omitempty" json:"user_id,omitempty"`
}

// ListGroupMembershipsParamsOrder defines parameters for ListGroupMemberships.
type ListGroupMembershipsParamsOrder string

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	Limit  *Limit                 `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset                `form:"offset,omitempty" json:"offset,omitempty"`
	Search *Search                `form:"search,omitempty" json:"search,omitempty"`
	Sort   *Sort                  `form:"sort,omitempty" json:"sort,omitempty"`
	Order  *ListGroupsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
}

// ListGroupsParamsOrder defines parameters for ListGroups.
type ListGroupsParamsOrder string

// ListLocationsParams defines parameters for ListLocations.
type ListLocationsParams struct {
	Limit   *Limit                    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset  *Offset                   `form:"offset,omitempty" json:"offset,omitempty"`
	Search  *Search                   `form:"search,omitempty" json:"search,omitempty"`
	Sort    *Sort                     `form:"sort,omitempty" json:"sort,omitempty"`
	Order   *ListLocationsParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	Enabled *EnabledFilter            `form:"enabled,omitempty" json:"enabled,omitempty"`
}

// ListLocationsParamsOrder defines parameters for ListLocations.
type ListLocationsParamsOrder string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Limit      *Limit                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset               `form:"offset,omitempty" json:"offset,omitempty"`
	Search     *Search               `form:"search,omitempty" json:"search,omitempty"`
	Sort       *Sort                 `form:"sort,omitempty" json:"sort,omitempty"`
	Order      *ListUsersParamsOrder `form:"order,omitempty" json:"order,omitempty"`
	LocationId *LocationIdFilter     `form:"location_id,omitempty" json:"location_id,omitempty"`
}

// ListUsersParamsOrder defines parameters for ListUsers.
type ListUsersParamsOrder string

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = APIKeyCreateRequest

// PatchAPIKeyJSONRequestBody defines body for PatchAPIKey for application/json ContentType.
type PatchAPIKeyJSONRequestBody = APIKeyAccessWriteRequest

// CreateAssetMultipartRequestBody defines body for CreateAsset for multipart/form-data ContentType.
type CreateAssetMultipartRequestBody = AssetCreateRequest

// PatchAssetMultipartRequestBody defines body for PatchAsset for multipart/form-data ContentType.
type PatchAssetMultipartRequestBody = AssetUpdateRequest

// CreateCheckinMultipartRequestBody defines body for CreateCheckin for multipart/form-data ContentType.
type CreateCheckinMultipartRequestBody = CheckinCreateRequest

// CreateLocationJSONRequestBody defines body for CreateLocation for application/json ContentType.
type CreateLocationJSONRequestBody = LocationWriteRequest

// PatchLocationJSONRequestBody defines body for PatchLocation for application/json ContentType.
type PatchLocationJSONRequestBody = LocationWriteRequest

// PatchUserJSONRequestBody defines body for PatchUser for application/json ContentType.
type PatchUserJSONRequestBody = UserAccessWriteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api-keys)
	ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams)

	// (POST /api-keys)
	CreateAPIKey(w http.ResponseWriter, r *http.Request)

	// (DELETE /api-keys/{id})
	DeleteAPIKey(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /api-keys/{id})
	GetAPIKey(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /api-keys/{id})
	PatchAPIKey(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /assets)
	ListAssets(w http.ResponseWriter, r *http.Request, params ListAssetsParams)

	// (POST /assets)
	CreateAsset(w http.ResponseWriter, r *http.Request)

	// (DELETE /assets/{id})
	DeleteAsset(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /assets/{id})
	GetAsset(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /assets/{id})
	PatchAsset(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /assets/{id}/content)
	GetAssetContent(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /checkins)
	ListCheckins(w http.ResponseWriter, r *http.Request, params ListCheckinsParams)

	// (POST /checkins)
	CreateCheckin(w http.ResponseWriter, r *http.Request)

	// (GET /checkins/{id})
	GetCheckin(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /group-memberships)
	ListGroupMemberships(w http.ResponseWriter, r *http.Request, params ListGroupMembershipsParams)

	// (GET /group-memberships/{id})
	GetGroupMembership(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /groups)
	ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams)

	// (GET /groups/{id})
	GetGroup(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /locations)
	ListLocations(w http.ResponseWriter, r *http.Request, params ListLocationsParams)

	// (POST /locations)
	CreateLocation(w http.ResponseWriter, r *http.Request)

	// (DELETE /locations/{id})
	DeleteLocation(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /locations/{id})
	GetLocation(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /locations/{id})
	PatchLocation(w http.ResponseWriter, r *http.Request, id Id)

	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)

	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id Id)

	// (PATCH /users/{id})
	PatchUser(w http.ResponseWriter, r *http.Request, id Id)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api-keys)
func (_ Unimplemented) ListAPIKeys(w http.ResponseWriter, r *http.Request, params ListAPIKeysParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api-keys)
func (_ Unimplemented) CreateAPIKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api-keys/{id})
func (_ Unimplemented) DeleteAPIKey(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api-keys/{id})
func (_ Unimplemented) GetAPIKey(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /api-keys/{id})
func (_ Unimplemented) PatchAPIKey(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets)
func (_ Unimplemented) ListAssets(w http.ResponseWriter, r *http.Request, params ListAssetsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /assets)
func (_ Unimplemented) CreateAsset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /assets/{id})
func (_ Unimplemented) DeleteAsset(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets/{id})
func (_ Unimplemented) GetAsset(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /assets/{id})
func (_ Unimplemented) PatchAsset(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /assets/{id}/content)
func (_ Unimplemented) GetAssetContent(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /checkins)
func (_ Unimplemented) ListCheckins(w http.ResponseWriter, r *http.Request, params ListCheckinsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /checkins)
func (_ Unimplemented) CreateCheckin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /checkins/{id})
func (_ Unimplemented) GetCheckin(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /group-memberships)
func (_ Unimplemented) ListGroupMemberships(w http.ResponseWriter, r *http.Request, params ListGroupMembershipsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /group-memberships/{id})
func (_ Unimplemented) GetGroupMembership(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups)
func (_ Unimplemented) ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /groups/{id})
func (_ Unimplemented) GetGroup(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /locations)
func (_ Unimplemented) ListLocations(w http.ResponseWriter, r *http.Request, params ListLocationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /locations)
func (_ Unimplemented) CreateLocation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /locations/{id})
func (_ Unimplemented) DeleteLocation(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /locations/{id})
func (_ Unimplemented) GetLocation(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /locations/{id})
func (_ Unimplemented) PatchLocation(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /users/{id})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PATCH /users/{id})
func (_ Unimplemented) PatchUser(w http.ResponseWriter, r *http.Request, id Id) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAPIKeys operation middleware
func (siw *ServerInterfaceWrapper) ListAPIKeys(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAPIKeysParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAPIKeys(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAPIKey operation middleware
func (siw *ServerInterfaceWrapper) CreateAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAPIKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAPIKey operation middleware
func (siw *ServerInterfaceWrapper) GetAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAPIKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAPIKey operation middleware
func (siw *ServerInterfaceWrapper) PatchAPIKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAPIKey(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAsset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAsset(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAsset operation middleware
func (siw *ServerInterfaceWrapper) PatchAsset(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAsset(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAssetContent operation middleware
func (siw *ServerInterfaceWrapper) GetAssetContent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAssetContent(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCheckins operation middleware
func (siw *ServerInterfaceWrapper) ListCheckins(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCheckinsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "location_id", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "location_id", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	// ------------- Optional query parameter "direction" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "direction", r.URL.Query(), &params.Direction, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "direction", Err: err})
		return
	}

	// ------------- Optional query parameter "created_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_from", r.URL.Query(), &params.CreatedFrom, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_from", Err: err})
		return
	}

	// ------------- Optional query parameter "created_to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_to", r.URL.Query(), &params.CreatedTo, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCheckins(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCheckin operation middleware
func (siw *ServerInterfaceWrapper) CreateCheckin(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCheckin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCheckin operation middleware
func (siw *ServerInterfaceWrapper) GetCheckin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCheckin(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroupMemberships operation middleware
func (siw *ServerInterfaceWrapper) ListGroupMemberships(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupMembershipsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_id", r.URL.Query(), &params.GroupId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "user_id", r.URL.Query(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupMemberships(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroupMembership operation middleware
func (siw *ServerInterfaceWrapper) GetGroupMembership(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroupMembership(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLocations operation middleware
func (siw *ServerInterfaceWrapper) ListLocations(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLocationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "enabled" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "enabled", r.URL.Query(), &params.Enabled, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "enabled", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLocations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLocation operation middleware
func (siw *ServerInterfaceWrapper) CreateLocation(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLocation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteLocation operation middleware
func (siw *ServerInterfaceWrapper) DeleteLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteLocation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLocation operation middleware
func (siw *ServerInterfaceWrapper) GetLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLocation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchLocation operation middleware
func (siw *ServerInterfaceWrapper) PatchLocation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchLocation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order", r.URL.Query(), &params.Order, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "order", Err: err})
		return
	}

	// ------------- Optional query parameter "location_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "location_id", r.URL.Query(), &params.LocationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "location_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchUser operation middleware
func (siw *ServerInterfaceWrapper) PatchUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Id

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api-keys", wrapper.ListAPIKeys)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-keys", wrapper.CreateAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api-keys/{id}", wrapper.DeleteAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api-keys/{id}", wrapper.GetAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api-keys/{id}", wrapper.PatchAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets", wrapper.ListAssets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/assets", wrapper.CreateAsset)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/assets/{id}", wrapper.DeleteAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}", wrapper.GetAsset)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/assets/{id}", wrapper.PatchAsset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/assets/{id}/content", wrapper.GetAssetContent)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/checkins", wrapper.ListCheckins)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/checkins", wrapper.CreateCheckin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/checkins/{id}", wrapper.GetCheckin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group-memberships", wrapper.ListGroupMemberships)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/group-memberships/{id}", wrapper.GetGroupMembership)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{id}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/locations", wrapper.ListLocations)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/locations", wrapper.CreateLocation)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/locations/{id}", wrapper.DeleteLocation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/locations/{id}", wrapper.GetLocation)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/locations/{id}", wrapper.PatchLocation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{id}", wrapper.PatchUser)
	})

	return r
}
