/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAppKeysRouteImport } from './routes/_authenticated/app-keys'
import { Route as AuthenticatedCheckinsRouteImport } from './routes/_authenticated/checkins'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedAppKeysIndexRouteImport } from './routes/_authenticated/app-keys.index'
import { Route as AuthenticatedAppKeysIdRouteImport } from './routes/_authenticated/app-keys.$id'
import { Route as AuthenticatedAppKeysNewRouteImport } from './routes/_authenticated/app-keys.new'
import { Route as AuthenticatedCheckinsIndexRouteImport } from './routes/_authenticated/checkins.index'
import { Route as AuthenticatedCheckinsIdRouteImport } from './routes/_authenticated/checkins.$id'
import { Route as AuthenticatedDirectoryIndexRouteImport } from './routes/_authenticated/directory.index'
import { Route as AuthenticatedDirectoryGroupsRouteImport } from './routes/_authenticated/directory.groups'
import { Route as AuthenticatedDirectoryUsersRouteImport } from './routes/_authenticated/directory.users'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedLocationsIdRouteImport } from './routes/_authenticated/locations.$id'
import { Route as AuthenticatedLocationsNewRouteImport } from './routes/_authenticated/locations.new'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles.index'
import { Route as AuthenticatedRolesIdRouteImport } from './routes/_authenticated/roles.$id'
import { Route as AuthenticatedRolesNewRouteImport } from './routes/_authenticated/roles.new'
import { Route as AuthenticatedAppKeysIdIndexRouteImport } from './routes/_authenticated/app-keys.$id.index'
import { Route as AuthenticatedAppKeysIdEditRouteImport } from './routes/_authenticated/app-keys.$id.edit'
import { Route as AuthenticatedDirectoryGroupsIndexRouteImport } from './routes/_authenticated/directory.groups.index'
import { Route as AuthenticatedDirectoryGroupsIdRouteImport } from './routes/_authenticated/directory.groups.$id'
import { Route as AuthenticatedDirectoryUsersIndexRouteImport } from './routes/_authenticated/directory.users.index'
import { Route as AuthenticatedDirectoryUsersIdRouteImport } from './routes/_authenticated/directory.users.$id'
import { Route as AuthenticatedDirectoryUsersNewRouteImport } from './routes/_authenticated/directory.users.new'
import { Route as AuthenticatedLocationsIdIndexRouteImport } from './routes/_authenticated/locations.$id.index'
import { Route as AuthenticatedLocationsIdEditRouteImport } from './routes/_authenticated/locations.$id.edit'
import { Route as AuthenticatedRolesIdIndexRouteImport } from './routes/_authenticated/roles.$id.index'
import { Route as AuthenticatedRolesIdEditRouteImport } from './routes/_authenticated/roles.$id.edit'
import { Route as AuthenticatedDirectoryGroupsIdIndexRouteImport } from './routes/_authenticated/directory.groups.$id.index'
import { Route as AuthenticatedDirectoryGroupsIdEditRouteImport } from './routes/_authenticated/directory.groups.$id.edit'
import { Route as AuthenticatedDirectoryUsersIdIndexRouteImport } from './routes/_authenticated/directory.users.$id.index'
import { Route as AuthenticatedDirectoryUsersIdEditRouteImport } from './routes/_authenticated/directory.users.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppKeysRoute = AuthenticatedAppKeysRouteImport.update({
  id: '/app-keys',
  path: '/app-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckinsRoute = AuthenticatedCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppKeysIndexRoute =
  AuthenticatedAppKeysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppKeysRoute,
  } as any)
const AuthenticatedAppKeysIdRoute = AuthenticatedAppKeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppKeysRoute,
} as any)
const AuthenticatedAppKeysNewRoute = AuthenticatedAppKeysNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAppKeysRoute,
} as any)
const AuthenticatedCheckinsIndexRoute =
  AuthenticatedCheckinsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCheckinsRoute,
  } as any)
const AuthenticatedCheckinsIdRoute = AuthenticatedCheckinsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCheckinsRoute,
} as any)
const AuthenticatedDirectoryIndexRoute =
  AuthenticatedDirectoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDirectoryRoute,
  } as any)
const AuthenticatedDirectoryGroupsRoute =
  AuthenticatedDirectoryGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedDirectoryRoute,
  } as any)
const AuthenticatedDirectoryUsersRoute =
  AuthenticatedDirectoryUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDirectoryRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLocationsRoute,
  } as any)
const AuthenticatedLocationsIdRoute =
  AuthenticatedLocationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLocationsRoute,
  } as any)
const AuthenticatedLocationsNewRoute =
  AuthenticatedLocationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedLocationsRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRolesRoute,
} as any)
const AuthenticatedRolesIdRoute = AuthenticatedRolesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRolesRoute,
} as any)
const AuthenticatedRolesNewRoute = AuthenticatedRolesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRolesRoute,
} as any)
const AuthenticatedAppKeysIdIndexRoute =
  AuthenticatedAppKeysIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppKeysIdRoute,
  } as any)
const AuthenticatedAppKeysIdEditRoute =
  AuthenticatedAppKeysIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedAppKeysIdRoute,
  } as any)
const AuthenticatedDirectoryGroupsIndexRoute =
  AuthenticatedDirectoryGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDirectoryGroupsRoute,
  } as any)
const AuthenticatedDirectoryGroupsIdRoute =
  AuthenticatedDirectoryGroupsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDirectoryGroupsRoute,
  } as any)
const AuthenticatedDirectoryUsersIndexRoute =
  AuthenticatedDirectoryUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDirectoryUsersRoute,
  } as any)
const AuthenticatedDirectoryUsersIdRoute =
  AuthenticatedDirectoryUsersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDirectoryUsersRoute,
  } as any)
const AuthenticatedDirectoryUsersNewRoute =
  AuthenticatedDirectoryUsersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDirectoryUsersRoute,
  } as any)
const AuthenticatedLocationsIdIndexRoute =
  AuthenticatedLocationsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLocationsIdRoute,
  } as any)
const AuthenticatedLocationsIdEditRoute =
  AuthenticatedLocationsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedLocationsIdRoute,
  } as any)
const AuthenticatedRolesIdIndexRoute =
  AuthenticatedRolesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRolesIdRoute,
  } as any)
const AuthenticatedRolesIdEditRoute =
  AuthenticatedRolesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedRolesIdRoute,
  } as any)
const AuthenticatedDirectoryGroupsIdIndexRoute =
  AuthenticatedDirectoryGroupsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDirectoryGroupsIdRoute,
  } as any)
const AuthenticatedDirectoryGroupsIdEditRoute =
  AuthenticatedDirectoryGroupsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDirectoryGroupsIdRoute,
  } as any)
const AuthenticatedDirectoryUsersIdIndexRoute =
  AuthenticatedDirectoryUsersIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDirectoryUsersIdRoute,
  } as any)
const AuthenticatedDirectoryUsersIdEditRoute =
  AuthenticatedDirectoryUsersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDirectoryUsersIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/app-keys': typeof AuthenticatedAppKeysRouteWithChildren
  '/checkins': typeof AuthenticatedCheckinsRouteWithChildren
  '/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/locations': typeof AuthenticatedLocationsRouteWithChildren
  '/roles': typeof AuthenticatedRolesRouteWithChildren
  '/app-keys/$id': typeof AuthenticatedAppKeysIdRouteWithChildren
  '/app-keys/new': typeof AuthenticatedAppKeysNewRoute
  '/checkins/$id': typeof AuthenticatedCheckinsIdRoute
  '/directory/groups': typeof AuthenticatedDirectoryGroupsRouteWithChildren
  '/directory/users': typeof AuthenticatedDirectoryUsersRouteWithChildren
  '/locations/$id': typeof AuthenticatedLocationsIdRouteWithChildren
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/roles/$id': typeof AuthenticatedRolesIdRouteWithChildren
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/app-keys/': typeof AuthenticatedAppKeysIndexRoute
  '/checkins/': typeof AuthenticatedCheckinsIndexRoute
  '/directory/': typeof AuthenticatedDirectoryIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/app-keys/$id/edit': typeof AuthenticatedAppKeysIdEditRoute
  '/directory/groups/$id': typeof AuthenticatedDirectoryGroupsIdRouteWithChildren
  '/directory/users/$id': typeof AuthenticatedDirectoryUsersIdRouteWithChildren
  '/directory/users/new': typeof AuthenticatedDirectoryUsersNewRoute
  '/locations/$id/edit': typeof AuthenticatedLocationsIdEditRoute
  '/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/app-keys/$id/': typeof AuthenticatedAppKeysIdIndexRoute
  '/directory/groups/': typeof AuthenticatedDirectoryGroupsIndexRoute
  '/directory/users/': typeof AuthenticatedDirectoryUsersIndexRoute
  '/locations/$id/': typeof AuthenticatedLocationsIdIndexRoute
  '/roles/$id/': typeof AuthenticatedRolesIdIndexRoute
  '/directory/groups/$id/edit': typeof AuthenticatedDirectoryGroupsIdEditRoute
  '/directory/users/$id/edit': typeof AuthenticatedDirectoryUsersIdEditRoute
  '/directory/groups/$id/': typeof AuthenticatedDirectoryGroupsIdIndexRoute
  '/directory/users/$id/': typeof AuthenticatedDirectoryUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/app-keys/new': typeof AuthenticatedAppKeysNewRoute
  '/checkins/$id': typeof AuthenticatedCheckinsIdRoute
  '/locations/new': typeof AuthenticatedLocationsNewRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/app-keys': typeof AuthenticatedAppKeysIndexRoute
  '/checkins': typeof AuthenticatedCheckinsIndexRoute
  '/directory': typeof AuthenticatedDirectoryIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/app-keys/$id/edit': typeof AuthenticatedAppKeysIdEditRoute
  '/directory/users/new': typeof AuthenticatedDirectoryUsersNewRoute
  '/locations/$id/edit': typeof AuthenticatedLocationsIdEditRoute
  '/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/app-keys/$id': typeof AuthenticatedAppKeysIdIndexRoute
  '/directory/groups': typeof AuthenticatedDirectoryGroupsIndexRoute
  '/directory/users': typeof AuthenticatedDirectoryUsersIndexRoute
  '/locations/$id': typeof AuthenticatedLocationsIdIndexRoute
  '/roles/$id': typeof AuthenticatedRolesIdIndexRoute
  '/directory/groups/$id/edit': typeof AuthenticatedDirectoryGroupsIdEditRoute
  '/directory/users/$id/edit': typeof AuthenticatedDirectoryUsersIdEditRoute
  '/directory/groups/$id': typeof AuthenticatedDirectoryGroupsIdIndexRoute
  '/directory/users/$id': typeof AuthenticatedDirectoryUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/app-keys': typeof AuthenticatedAppKeysRouteWithChildren
  '/_authenticated/checkins': typeof AuthenticatedCheckinsRouteWithChildren
  '/_authenticated/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/_authenticated/locations': typeof AuthenticatedLocationsRouteWithChildren
  '/_authenticated/roles': typeof AuthenticatedRolesRouteWithChildren
  '/_authenticated/app-keys/$id': typeof AuthenticatedAppKeysIdRouteWithChildren
  '/_authenticated/app-keys/new': typeof AuthenticatedAppKeysNewRoute
  '/_authenticated/checkins/$id': typeof AuthenticatedCheckinsIdRoute
  '/_authenticated/directory/groups': typeof AuthenticatedDirectoryGroupsRouteWithChildren
  '/_authenticated/directory/users': typeof AuthenticatedDirectoryUsersRouteWithChildren
  '/_authenticated/locations/$id': typeof AuthenticatedLocationsIdRouteWithChildren
  '/_authenticated/locations/new': typeof AuthenticatedLocationsNewRoute
  '/_authenticated/roles/$id': typeof AuthenticatedRolesIdRouteWithChildren
  '/_authenticated/roles/new': typeof AuthenticatedRolesNewRoute
  '/_authenticated/app-keys/': typeof AuthenticatedAppKeysIndexRoute
  '/_authenticated/checkins/': typeof AuthenticatedCheckinsIndexRoute
  '/_authenticated/directory/': typeof AuthenticatedDirectoryIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/app-keys/$id/edit': typeof AuthenticatedAppKeysIdEditRoute
  '/_authenticated/directory/groups/$id': typeof AuthenticatedDirectoryGroupsIdRouteWithChildren
  '/_authenticated/directory/users/$id': typeof AuthenticatedDirectoryUsersIdRouteWithChildren
  '/_authenticated/directory/users/new': typeof AuthenticatedDirectoryUsersNewRoute
  '/_authenticated/locations/$id/edit': typeof AuthenticatedLocationsIdEditRoute
  '/_authenticated/roles/$id/edit': typeof AuthenticatedRolesIdEditRoute
  '/_authenticated/app-keys/$id/': typeof AuthenticatedAppKeysIdIndexRoute
  '/_authenticated/directory/groups/': typeof AuthenticatedDirectoryGroupsIndexRoute
  '/_authenticated/directory/users/': typeof AuthenticatedDirectoryUsersIndexRoute
  '/_authenticated/locations/$id/': typeof AuthenticatedLocationsIdIndexRoute
  '/_authenticated/roles/$id/': typeof AuthenticatedRolesIdIndexRoute
  '/_authenticated/directory/groups/$id/edit': typeof AuthenticatedDirectoryGroupsIdEditRoute
  '/_authenticated/directory/users/$id/edit': typeof AuthenticatedDirectoryUsersIdEditRoute
  '/_authenticated/directory/groups/$id/': typeof AuthenticatedDirectoryGroupsIdIndexRoute
  '/_authenticated/directory/users/$id/': typeof AuthenticatedDirectoryUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/app-keys'
    | '/checkins'
    | '/directory'
    | '/locations'
    | '/roles'
    | '/app-keys/$id'
    | '/app-keys/new'
    | '/checkins/$id'
    | '/directory/groups'
    | '/directory/users'
    | '/locations/$id'
    | '/locations/new'
    | '/roles/$id'
    | '/roles/new'
    | '/app-keys/'
    | '/checkins/'
    | '/directory/'
    | '/locations/'
    | '/roles/'
    | '/app-keys/$id/edit'
    | '/directory/groups/$id'
    | '/directory/users/$id'
    | '/directory/users/new'
    | '/locations/$id/edit'
    | '/roles/$id/edit'
    | '/app-keys/$id/'
    | '/directory/groups/'
    | '/directory/users/'
    | '/locations/$id/'
    | '/roles/$id/'
    | '/directory/groups/$id/edit'
    | '/directory/users/$id/edit'
    | '/directory/groups/$id/'
    | '/directory/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/app-keys/new'
    | '/checkins/$id'
    | '/locations/new'
    | '/roles/new'
    | '/app-keys'
    | '/checkins'
    | '/directory'
    | '/locations'
    | '/roles'
    | '/app-keys/$id/edit'
    | '/directory/users/new'
    | '/locations/$id/edit'
    | '/roles/$id/edit'
    | '/app-keys/$id'
    | '/directory/groups'
    | '/directory/users'
    | '/locations/$id'
    | '/roles/$id'
    | '/directory/groups/$id/edit'
    | '/directory/users/$id/edit'
    | '/directory/groups/$id'
    | '/directory/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/app-keys'
    | '/_authenticated/checkins'
    | '/_authenticated/directory'
    | '/_authenticated/locations'
    | '/_authenticated/roles'
    | '/_authenticated/app-keys/$id'
    | '/_authenticated/app-keys/new'
    | '/_authenticated/checkins/$id'
    | '/_authenticated/directory/groups'
    | '/_authenticated/directory/users'
    | '/_authenticated/locations/$id'
    | '/_authenticated/locations/new'
    | '/_authenticated/roles/$id'
    | '/_authenticated/roles/new'
    | '/_authenticated/app-keys/'
    | '/_authenticated/checkins/'
    | '/_authenticated/directory/'
    | '/_authenticated/locations/'
    | '/_authenticated/roles/'
    | '/_authenticated/app-keys/$id/edit'
    | '/_authenticated/directory/groups/$id'
    | '/_authenticated/directory/users/$id'
    | '/_authenticated/directory/users/new'
    | '/_authenticated/locations/$id/edit'
    | '/_authenticated/roles/$id/edit'
    | '/_authenticated/app-keys/$id/'
    | '/_authenticated/directory/groups/'
    | '/_authenticated/directory/users/'
    | '/_authenticated/locations/$id/'
    | '/_authenticated/roles/$id/'
    | '/_authenticated/directory/groups/$id/edit'
    | '/_authenticated/directory/users/$id/edit'
    | '/_authenticated/directory/groups/$id/'
    | '/_authenticated/directory/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-keys': {
      id: '/_authenticated/app-keys'
      path: '/app-keys'
      fullPath: '/app-keys'
      preLoaderRoute: typeof AuthenticatedAppKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkins': {
      id: '/_authenticated/checkins'
      path: '/checkins'
      fullPath: '/checkins'
      preLoaderRoute: typeof AuthenticatedCheckinsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-keys/': {
      id: '/_authenticated/app-keys/'
      path: '/'
      fullPath: '/app-keys/'
      preLoaderRoute: typeof AuthenticatedAppKeysIndexRouteImport
      parentRoute: typeof AuthenticatedAppKeysRoute
    }
    '/_authenticated/app-keys/$id': {
      id: '/_authenticated/app-keys/$id'
      path: '/$id'
      fullPath: '/app-keys/$id'
      preLoaderRoute: typeof AuthenticatedAppKeysIdRouteImport
      parentRoute: typeof AuthenticatedAppKeysRoute
    }
    '/_authenticated/app-keys/new': {
      id: '/_authenticated/app-keys/new'
      path: '/new'
      fullPath: '/app-keys/new'
      preLoaderRoute: typeof AuthenticatedAppKeysNewRouteImport
      parentRoute: typeof AuthenticatedAppKeysRoute
    }
    '/_authenticated/checkins/': {
      id: '/_authenticated/checkins/'
      path: '/'
      fullPath: '/checkins/'
      preLoaderRoute: typeof AuthenticatedCheckinsIndexRouteImport
      parentRoute: typeof AuthenticatedCheckinsRoute
    }
    '/_authenticated/checkins/$id': {
      id: '/_authenticated/checkins/$id'
      path: '/$id'
      fullPath: '/checkins/$id'
      preLoaderRoute: typeof AuthenticatedCheckinsIdRouteImport
      parentRoute: typeof AuthenticatedCheckinsRoute
    }
    '/_authenticated/directory/': {
      id: '/_authenticated/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthenticatedDirectoryIndexRouteImport
      parentRoute: typeof AuthenticatedDirectoryRoute
    }
    '/_authenticated/directory/groups': {
      id: '/_authenticated/directory/groups'
      path: '/groups'
      fullPath: '/directory/groups'
      preLoaderRoute: typeof AuthenticatedDirectoryGroupsRouteImport
      parentRoute: typeof AuthenticatedDirectoryRoute
    }
    '/_authenticated/directory/users': {
      id: '/_authenticated/directory/users'
      path: '/users'
      fullPath: '/directory/users'
      preLoaderRoute: typeof AuthenticatedDirectoryUsersRouteImport
      parentRoute: typeof AuthenticatedDirectoryRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedLocationsRoute
    }
    '/_authenticated/locations/$id': {
      id: '/_authenticated/locations/$id'
      path: '/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof AuthenticatedLocationsIdRouteImport
      parentRoute: typeof AuthenticatedLocationsRoute
    }
    '/_authenticated/locations/new': {
      id: '/_authenticated/locations/new'
      path: '/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AuthenticatedLocationsNewRouteImport
      parentRoute: typeof AuthenticatedLocationsRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/roles/$id': {
      id: '/_authenticated/roles/$id'
      path: '/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthenticatedRolesIdRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/roles/new': {
      id: '/_authenticated/roles/new'
      path: '/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthenticatedRolesNewRouteImport
      parentRoute: typeof AuthenticatedRolesRoute
    }
    '/_authenticated/app-keys/$id/': {
      id: '/_authenticated/app-keys/$id/'
      path: '/'
      fullPath: '/app-keys/$id/'
      preLoaderRoute: typeof AuthenticatedAppKeysIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppKeysIdRoute
    }
    '/_authenticated/app-keys/$id/edit': {
      id: '/_authenticated/app-keys/$id/edit'
      path: '/edit'
      fullPath: '/app-keys/$id/edit'
      preLoaderRoute: typeof AuthenticatedAppKeysIdEditRouteImport
      parentRoute: typeof AuthenticatedAppKeysIdRoute
    }
    '/_authenticated/directory/groups/': {
      id: '/_authenticated/directory/groups/'
      path: '/'
      fullPath: '/directory/groups/'
      preLoaderRoute: typeof AuthenticatedDirectoryGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedDirectoryGroupsRoute
    }
    '/_authenticated/directory/groups/$id': {
      id: '/_authenticated/directory/groups/$id'
      path: '/$id'
      fullPath: '/directory/groups/$id'
      preLoaderRoute: typeof AuthenticatedDirectoryGroupsIdRouteImport
      parentRoute: typeof AuthenticatedDirectoryGroupsRoute
    }
    '/_authenticated/directory/users/': {
      id: '/_authenticated/directory/users/'
      path: '/'
      fullPath: '/directory/users/'
      preLoaderRoute: typeof AuthenticatedDirectoryUsersIndexRouteImport
      parentRoute: typeof AuthenticatedDirectoryUsersRoute
    }
    '/_authenticated/directory/users/$id': {
      id: '/_authenticated/directory/users/$id'
      path: '/$id'
      fullPath: '/directory/users/$id'
      preLoaderRoute: typeof AuthenticatedDirectoryUsersIdRouteImport
      parentRoute: typeof AuthenticatedDirectoryUsersRoute
    }
    '/_authenticated/directory/users/new': {
      id: '/_authenticated/directory/users/new'
      path: '/new'
      fullPath: '/directory/users/new'
      preLoaderRoute: typeof AuthenticatedDirectoryUsersNewRouteImport
      parentRoute: typeof AuthenticatedDirectoryUsersRoute
    }
    '/_authenticated/locations/$id/': {
      id: '/_authenticated/locations/$id/'
      path: '/'
      fullPath: '/locations/$id/'
      preLoaderRoute: typeof AuthenticatedLocationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedLocationsIdRoute
    }
    '/_authenticated/locations/$id/edit': {
      id: '/_authenticated/locations/$id/edit'
      path: '/edit'
      fullPath: '/locations/$id/edit'
      preLoaderRoute: typeof AuthenticatedLocationsIdEditRouteImport
      parentRoute: typeof AuthenticatedLocationsIdRoute
    }
    '/_authenticated/roles/$id/': {
      id: '/_authenticated/roles/$id/'
      path: '/'
      fullPath: '/roles/$id/'
      preLoaderRoute: typeof AuthenticatedRolesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRolesIdRoute
    }
    '/_authenticated/roles/$id/edit': {
      id: '/_authenticated/roles/$id/edit'
      path: '/edit'
      fullPath: '/roles/$id/edit'
      preLoaderRoute: typeof AuthenticatedRolesIdEditRouteImport
      parentRoute: typeof AuthenticatedRolesIdRoute
    }
    '/_authenticated/directory/groups/$id/': {
      id: '/_authenticated/directory/groups/$id/'
      path: '/'
      fullPath: '/directory/groups/$id/'
      preLoaderRoute: typeof AuthenticatedDirectoryGroupsIdIndexRouteImport
      parentRoute: typeof AuthenticatedDirectoryGroupsIdRoute
    }
    '/_authenticated/directory/groups/$id/edit': {
      id: '/_authenticated/directory/groups/$id/edit'
      path: '/edit'
      fullPath: '/directory/groups/$id/edit'
      preLoaderRoute: typeof AuthenticatedDirectoryGroupsIdEditRouteImport
      parentRoute: typeof AuthenticatedDirectoryGroupsIdRoute
    }
    '/_authenticated/directory/users/$id/': {
      id: '/_authenticated/directory/users/$id/'
      path: '/'
      fullPath: '/directory/users/$id/'
      preLoaderRoute: typeof AuthenticatedDirectoryUsersIdIndexRouteImport
      parentRoute: typeof AuthenticatedDirectoryUsersIdRoute
    }
    '/_authenticated/directory/users/$id/edit': {
      id: '/_authenticated/directory/users/$id/edit'
      path: '/edit'
      fullPath: '/directory/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedDirectoryUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedDirectoryUsersIdRoute
    }
  }
}

interface AuthenticatedAppKeysIdRouteChildren {
  AuthenticatedAppKeysIdEditRoute: typeof AuthenticatedAppKeysIdEditRoute
  AuthenticatedAppKeysIdIndexRoute: typeof AuthenticatedAppKeysIdIndexRoute
}

const AuthenticatedAppKeysIdRouteChildren: AuthenticatedAppKeysIdRouteChildren =
  {
    AuthenticatedAppKeysIdEditRoute: AuthenticatedAppKeysIdEditRoute,
    AuthenticatedAppKeysIdIndexRoute: AuthenticatedAppKeysIdIndexRoute,
  }

const AuthenticatedAppKeysIdRouteWithChildren =
  AuthenticatedAppKeysIdRoute._addFileChildren(
    AuthenticatedAppKeysIdRouteChildren,
  )

interface AuthenticatedAppKeysRouteChildren {
  AuthenticatedAppKeysIdRoute: typeof AuthenticatedAppKeysIdRouteWithChildren
  AuthenticatedAppKeysNewRoute: typeof AuthenticatedAppKeysNewRoute
  AuthenticatedAppKeysIndexRoute: typeof AuthenticatedAppKeysIndexRoute
}

const AuthenticatedAppKeysRouteChildren: AuthenticatedAppKeysRouteChildren = {
  AuthenticatedAppKeysIdRoute: AuthenticatedAppKeysIdRouteWithChildren,
  AuthenticatedAppKeysNewRoute: AuthenticatedAppKeysNewRoute,
  AuthenticatedAppKeysIndexRoute: AuthenticatedAppKeysIndexRoute,
}

const AuthenticatedAppKeysRouteWithChildren =
  AuthenticatedAppKeysRoute._addFileChildren(AuthenticatedAppKeysRouteChildren)

interface AuthenticatedCheckinsRouteChildren {
  AuthenticatedCheckinsIdRoute: typeof AuthenticatedCheckinsIdRoute
  AuthenticatedCheckinsIndexRoute: typeof AuthenticatedCheckinsIndexRoute
}

const AuthenticatedCheckinsRouteChildren: AuthenticatedCheckinsRouteChildren = {
  AuthenticatedCheckinsIdRoute: AuthenticatedCheckinsIdRoute,
  AuthenticatedCheckinsIndexRoute: AuthenticatedCheckinsIndexRoute,
}

const AuthenticatedCheckinsRouteWithChildren =
  AuthenticatedCheckinsRoute._addFileChildren(
    AuthenticatedCheckinsRouteChildren,
  )

interface AuthenticatedDirectoryGroupsIdRouteChildren {
  AuthenticatedDirectoryGroupsIdEditRoute: typeof AuthenticatedDirectoryGroupsIdEditRoute
  AuthenticatedDirectoryGroupsIdIndexRoute: typeof AuthenticatedDirectoryGroupsIdIndexRoute
}

const AuthenticatedDirectoryGroupsIdRouteChildren: AuthenticatedDirectoryGroupsIdRouteChildren =
  {
    AuthenticatedDirectoryGroupsIdEditRoute:
      AuthenticatedDirectoryGroupsIdEditRoute,
    AuthenticatedDirectoryGroupsIdIndexRoute:
      AuthenticatedDirectoryGroupsIdIndexRoute,
  }

const AuthenticatedDirectoryGroupsIdRouteWithChildren =
  AuthenticatedDirectoryGroupsIdRoute._addFileChildren(
    AuthenticatedDirectoryGroupsIdRouteChildren,
  )

interface AuthenticatedDirectoryGroupsRouteChildren {
  AuthenticatedDirectoryGroupsIdRoute: typeof AuthenticatedDirectoryGroupsIdRouteWithChildren
  AuthenticatedDirectoryGroupsIndexRoute: typeof AuthenticatedDirectoryGroupsIndexRoute
}

const AuthenticatedDirectoryGroupsRouteChildren: AuthenticatedDirectoryGroupsRouteChildren =
  {
    AuthenticatedDirectoryGroupsIdRoute:
      AuthenticatedDirectoryGroupsIdRouteWithChildren,
    AuthenticatedDirectoryGroupsIndexRoute:
      AuthenticatedDirectoryGroupsIndexRoute,
  }

const AuthenticatedDirectoryGroupsRouteWithChildren =
  AuthenticatedDirectoryGroupsRoute._addFileChildren(
    AuthenticatedDirectoryGroupsRouteChildren,
  )

interface AuthenticatedDirectoryUsersIdRouteChildren {
  AuthenticatedDirectoryUsersIdEditRoute: typeof AuthenticatedDirectoryUsersIdEditRoute
  AuthenticatedDirectoryUsersIdIndexRoute: typeof AuthenticatedDirectoryUsersIdIndexRoute
}

const AuthenticatedDirectoryUsersIdRouteChildren: AuthenticatedDirectoryUsersIdRouteChildren =
  {
    AuthenticatedDirectoryUsersIdEditRoute:
      AuthenticatedDirectoryUsersIdEditRoute,
    AuthenticatedDirectoryUsersIdIndexRoute:
      AuthenticatedDirectoryUsersIdIndexRoute,
  }

const AuthenticatedDirectoryUsersIdRouteWithChildren =
  AuthenticatedDirectoryUsersIdRoute._addFileChildren(
    AuthenticatedDirectoryUsersIdRouteChildren,
  )

interface AuthenticatedDirectoryUsersRouteChildren {
  AuthenticatedDirectoryUsersIdRoute: typeof AuthenticatedDirectoryUsersIdRouteWithChildren
  AuthenticatedDirectoryUsersNewRoute: typeof AuthenticatedDirectoryUsersNewRoute
  AuthenticatedDirectoryUsersIndexRoute: typeof AuthenticatedDirectoryUsersIndexRoute
}

const AuthenticatedDirectoryUsersRouteChildren: AuthenticatedDirectoryUsersRouteChildren =
  {
    AuthenticatedDirectoryUsersIdRoute:
      AuthenticatedDirectoryUsersIdRouteWithChildren,
    AuthenticatedDirectoryUsersNewRoute: AuthenticatedDirectoryUsersNewRoute,
    AuthenticatedDirectoryUsersIndexRoute:
      AuthenticatedDirectoryUsersIndexRoute,
  }

const AuthenticatedDirectoryUsersRouteWithChildren =
  AuthenticatedDirectoryUsersRoute._addFileChildren(
    AuthenticatedDirectoryUsersRouteChildren,
  )

interface AuthenticatedDirectoryRouteChildren {
  AuthenticatedDirectoryGroupsRoute: typeof AuthenticatedDirectoryGroupsRouteWithChildren
  AuthenticatedDirectoryUsersRoute: typeof AuthenticatedDirectoryUsersRouteWithChildren
  AuthenticatedDirectoryIndexRoute: typeof AuthenticatedDirectoryIndexRoute
}

const AuthenticatedDirectoryRouteChildren: AuthenticatedDirectoryRouteChildren =
  {
    AuthenticatedDirectoryGroupsRoute:
      AuthenticatedDirectoryGroupsRouteWithChildren,
    AuthenticatedDirectoryUsersRoute:
      AuthenticatedDirectoryUsersRouteWithChildren,
    AuthenticatedDirectoryIndexRoute: AuthenticatedDirectoryIndexRoute,
  }

const AuthenticatedDirectoryRouteWithChildren =
  AuthenticatedDirectoryRoute._addFileChildren(
    AuthenticatedDirectoryRouteChildren,
  )

interface AuthenticatedLocationsIdRouteChildren {
  AuthenticatedLocationsIdEditRoute: typeof AuthenticatedLocationsIdEditRoute
  AuthenticatedLocationsIdIndexRoute: typeof AuthenticatedLocationsIdIndexRoute
}

const AuthenticatedLocationsIdRouteChildren: AuthenticatedLocationsIdRouteChildren =
  {
    AuthenticatedLocationsIdEditRoute: AuthenticatedLocationsIdEditRoute,
    AuthenticatedLocationsIdIndexRoute: AuthenticatedLocationsIdIndexRoute,
  }

const AuthenticatedLocationsIdRouteWithChildren =
  AuthenticatedLocationsIdRoute._addFileChildren(
    AuthenticatedLocationsIdRouteChildren,
  )

interface AuthenticatedLocationsRouteChildren {
  AuthenticatedLocationsIdRoute: typeof AuthenticatedLocationsIdRouteWithChildren
  AuthenticatedLocationsNewRoute: typeof AuthenticatedLocationsNewRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
}

const AuthenticatedLocationsRouteChildren: AuthenticatedLocationsRouteChildren =
  {
    AuthenticatedLocationsIdRoute: AuthenticatedLocationsIdRouteWithChildren,
    AuthenticatedLocationsNewRoute: AuthenticatedLocationsNewRoute,
    AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  }

const AuthenticatedLocationsRouteWithChildren =
  AuthenticatedLocationsRoute._addFileChildren(
    AuthenticatedLocationsRouteChildren,
  )

interface AuthenticatedRolesIdRouteChildren {
  AuthenticatedRolesIdEditRoute: typeof AuthenticatedRolesIdEditRoute
  AuthenticatedRolesIdIndexRoute: typeof AuthenticatedRolesIdIndexRoute
}

const AuthenticatedRolesIdRouteChildren: AuthenticatedRolesIdRouteChildren = {
  AuthenticatedRolesIdEditRoute: AuthenticatedRolesIdEditRoute,
  AuthenticatedRolesIdIndexRoute: AuthenticatedRolesIdIndexRoute,
}

const AuthenticatedRolesIdRouteWithChildren =
  AuthenticatedRolesIdRoute._addFileChildren(AuthenticatedRolesIdRouteChildren)

interface AuthenticatedRolesRouteChildren {
  AuthenticatedRolesIdRoute: typeof AuthenticatedRolesIdRouteWithChildren
  AuthenticatedRolesNewRoute: typeof AuthenticatedRolesNewRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
}

const AuthenticatedRolesRouteChildren: AuthenticatedRolesRouteChildren = {
  AuthenticatedRolesIdRoute: AuthenticatedRolesIdRouteWithChildren,
  AuthenticatedRolesNewRoute: AuthenticatedRolesNewRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
}

const AuthenticatedRolesRouteWithChildren =
  AuthenticatedRolesRoute._addFileChildren(AuthenticatedRolesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAppKeysRoute: typeof AuthenticatedAppKeysRouteWithChildren
  AuthenticatedCheckinsRoute: typeof AuthenticatedCheckinsRouteWithChildren
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRouteWithChildren
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRouteWithChildren
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAppKeysRoute: AuthenticatedAppKeysRouteWithChildren,
  AuthenticatedCheckinsRoute: AuthenticatedCheckinsRouteWithChildren,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRouteWithChildren,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRouteWithChildren,
  AuthenticatedRolesRoute: AuthenticatedRolesRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
