---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name != 'release' }}

jobs:
  release:
    name: Release
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: docker/github-builder/.github/workflows/build.yml@27ade872c1e2296e62ef15ab3b10d37665e57cf7 # v1.15.0
    with:
      cache: true
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=rolling,enable=${{ github.event_name == 'release' }}
        type=ref,event=branch
      output: image
      platforms: linux/amd64,linux/arm64
      push: true
      sbom: true
      set-meta-annotations: true
      set-meta-labels: true
      sign: true
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
